### ISSUE TITLE
Quest section 7 reporting "undefined"

### ISSUE THREAD

**Issue by GlitchMonkey** [MyM-ModpackTeam/GalacticScience#1]
Quest book showing quest section 7 as "undefined" for the first quest. I just updated the pack but I am not sure how to find what pack version this is. mymlauncher installed.

**Comment by GlitchMonkey** [comment]
Looks like the version is 1.2.0-0, found in the instance.json file.

**Comment by SirWilli** [comment]
Thanks for the report.

You probably mean this quest or?
![](http://i.imgur.com/Z6MGsWA.png)

Already fixed in 1.3.0

Modpack version will be visible in the main menu with version 1.3

**Comment by GlitchMonkey** [comment]
Thank you. I thought 1.3 was released but then after I submitted this I noticed on the forum that it was retracted. OOPS. Can't wait for 1.3 to go live.

**Comment by SirWilli** [comment]
Yea, we unfortunately have few gamebreaking bugs in 1.3 atm.
