### ISSUE TITLE
Invalid Thermal Protection ?

### ISSUE THREAD

**Issue by CedTecMinecraft** [MyM-ModpackTeam/GalacticScience#100]
Whenever I go on any other planet then mars (and the moon) I keep on getting damaged even if I have the thermal padding armor on...

And when I die it says : CedTec forgot his thermal protection ! (something in those lines)

**Comment by SirWilli** [comment]
Modpack version?

**Comment by CedTecMinecraft** [comment]
1.5.7 and also 1.5.8 
But really... I've seen other people do it... have I missed something ?

**Comment by SirWilli** [comment]
What do you mean?
Do you have an thermal armor on?

**Comment by CedTecMinecraft** [comment]
Yes... wearing full thermal padding...
http://wiki.micdoodle8.com/wiki/Thermal_Padding
I dunno what the issue is... works on mars and the moon, but fails for all the other planets

**Comment by CedTecMinecraft** [comment]
Same issue as this, seems like
https://github.com/4Space/4Space-1.7/issues/37

**Comment by SirWilli** [comment]
Hm, are you sure you have the issue on 1.5.8? As I fixed that issue in: https://github.com/MyM-ModpackTeam/GalacticScience/commit/82f1af90f7ee4d057b2227692ce058b5a7a267ea

What version of 4Space do you have in your folder and what launcher are you using?

**Comment by B3r6ur** [comment]
thx for this custom version, it solved my problem with getting damage for now
for me, i used 4Space-4.1.9 before and it did not work with that version.
