### ISSUE TITLE
quest unclaimable

### ISSUE THREAD

**Issue by Ethern8ai** [MyM-ModpackTeam/GalacticScience#101]
Hi the bug is that i cant finish steady supply and sorting storage upgrade, i can see the quest requests valid but no button to get the reward, seem to be a fix bug, same on 2 saves.

and is it normal that the trashcan 2.0 quest dont unlock the next ones?

great modpack good luck, pacience and keep on blockin'g ^^

**Comment by SirWilli** [comment]
Modpack version? Does it work with a fresh world?

**Comment by Ethern8ai** [comment]
its 1.5.7 and i fixed the storing one by crafting a secound one

the trashcan 2.0 is a bug or id does not unlock more "more power" quests?

and the steady supply its not very a hard one it just didnt gave me the stack of glowstone but let me keep on the next quest ^^

**Comment by SirWilli** [comment]
Please test it in the 1.5.8 update.
