### ISSUE TITLE
PC crashed and the whole world is defect

### ISSUE THREAD

**Issue by suko8** [MyM-ModpackTeam/GalacticScience#102]
Hello,

I was playing the Modpack, after a few hours my PC crashed (dont know why), so I started my Server and my Client again, all is fine but after the Server-Loading my Server crashes. And I dont know why, I tried to remove mods to see which one it is but this didnt helped. Me and my Friends wouldn't like to start over again. Here the Crash-Report

From yesterday.
[crash-2016-02-15_18.29.39-server.txt](https://github.com/MyM-ModpackTeam/GalacticScience/files/132344/crash-2016-02-15_18.29.39-server.txt)
From today.
[crash-2016-02-16_11.19.10-server.txt](https://github.com/MyM-ModpackTeam/GalacticScience/files/132347/crash-2016-02-16_11.19.10-server.txt)

Would be awesome if someone could help!

suko8

**Comment by SirWilli** [comment]
ModularSystems is causing the issue. I recommend to remove that mod.

**Comment by suko8** [comment]
will check it now, i'll write back later, if it works!

**Comment by suko8** [comment]
So I started the Server, all was fine but it crashed again, I checked the crash-report again and saw much issues with HardcoreQuestingMod, so I removed it too, now the Server easily starts without any issues. And of course I had to remove the HQM configs in the config and in the world folder.

Thanks mate, you helped me out at this :+1: both where the issue-maker^^

suko8

**Comment by SirWilli** [comment]
Delete the HardCoreQuestiong folder in your world folder and HQM should work again.

**Comment by suko8** [comment]
I did it, writed it already^^ but there isnt a way to recover the achievements? Well Im not that far but it is a little stupid. But hey the Server is running now without issues, really appreciate your help!

suko8

**Comment by SirWilli** [comment]
Achievements? You mean your quest progress? You could run /hqm edit to complete all quests manually.

**Comment by suko8** [comment]
Ah thanks you :D

suko8
