### ISSUE TITLE
Gamen wont start (SoundEngine)

### ISSUE THREAD

**Issue by sp44tz** [MyM-ModpackTeam/GalacticScience#109]
Most of the time, when i start the game, it stops loading at "Initializing Mincraft Engine - Rendering Setup Render global Instance"
Q the FTB - Luncher Conlose the last entry is: "Sound engine started" 
then the game go into "not responding" 

http://paste.feed-the-beast.com/view/47e3b5ff

**Comment by SirWilli** [comment]
- Reinstall the modpack
- Reinstall java
- Try other modpacks

Have you done that already?

**Comment by sp44tz** [comment]
other modpacks work fine
yes. also tried older versions of the pack.
sumtimes ~ after 20 times killin the mc-process and redownloading the files it works. -> when i restart it wit dont work anymore -.-

**Comment by SirWilli** [comment]
Hm, no idea what the issue is then.

**Comment by sp44tz** [comment]
the most disturbing thing is, that it sometimes work.
aktually i think Im at the 30th restart... but it wont work.

Most of the time it's the "rendering setup" - Freezz

but somethimes it crashes otherwise.

**Comment by sp44tz** [comment]
SO now im using FTb - Beta -> with Curse => 3 of 3 Times the game Started.

I guess it was a Bug in the GameLoader Engine of the old FTB Luncher?
-> Thread closed :)
