### ISSUE TITLE
sag mill duping?

### ISSUE THREAD

**Issue by JarlGiga** [MyM-ModpackTeam/GalacticScience#11]
i found a way to basicly dup silicon for abit of energy.

sandstone in the synthesizer cost 16 silicon dioxide, then sag mill the sandstone to get 3-4 sand, roughly, then decompose the sand for 1 sand = 16 silicon dioxide, and repeate.

so i was wondering if the recipe for sandstone should be made to 64 silicon dioxide or if you are leave it as is?

**Comment by drz2k** [comment]
When youre at T2 i think the energy and time you loose doing this far outweights the benefit. You could simply put cobble into the sagmill and swim in SiO2 too.

**Comment by drz2k** [comment]
Would label this as minor if we had the label ;)

**Comment by JarlGiga** [comment]
alright, just wanned to run it by you guys :)

**Comment by drz2k** [comment]
Thx for the feedback and whee heres my minor label :)
