### ISSUE TITLE
spawner don't work

### ISSUE THREAD

**Issue by k1ng1905** [MyM-ModpackTeam/GalacticScience#112]
version:1.5.8
the spawner are not work in dungeons or if i take it to moon with a dolly any suggestions what i can do?
(multiplayer)

**Comment by oodgaard** [comment]
I believe this is probably intended to make it harder.

**Comment by drz2k** [comment]
Wasnt directly intended but is perfectly okay with me to force the player the killer joe route ;)

**Comment by welard** [comment]
i was startig to enjoy this mod but whats the point of dungons if there is only one boss to kill and not a ton of mobs this makes the game a loteasyer and has killed my view of the game because of this small bug

**Comment by drz2k** [comment]
This is not in any manner an exploration type pack. 
If the configs would allow it, moon dungeons would be gone ...
If this already killing the game for you, perhaps settle with something else ;)
