### ISSUE TITLE
Refined Relocation sorting barrels need resetting after server restart

### ISSUE THREAD

**Issue by oodgaard** [MyM-ModpackTeam/GalacticScience#114]
In 1.5.9 of the pack, every time I restart my server I have to replace (pick up and put down) every sorting barrel for the sorting chest to see them.

**Comment by oodgaard** [comment]
Opis says Advanced Generators Gas Turbines have a large update time. Again, this is only when I'm away from the moon.

**Comment by oodgaard** [comment]
Just removed the dimensional anchor and tried ChickenChunks loader, no more lag. Clearly the dimensional anchor has an issue with something. That's a real pity since ChickenChunks makes it a bit easy since it will run when users are offline.

**Comment by Zeldinator** [comment]
Same here, but with every Sorting Inventory, even the Standard Wooden Sorting Chest.

**Comment by drz2k** [comment]
Mod issue - should be reported to the mod creator but i fear he isnt caring that much for the issues ...
