### ISSUE TITLE
world don't load in smp

### ISSUE THREAD

**Issue by nidico100** [MyM-ModpackTeam/GalacticScience#116]
Hey, 
I can play in Singleplayer just fine. Then I downloaded the Server via FTB and started it. I can join, get the startgear and have the HUD, but no block is loading. I'm just in the middle of nowhere. The Server is running at 4GB DD3 Ram and on an Intel Core 3770K @3,5GHz localhost. I can't give a log or something, because it doesn't crash or anything else. Just after quite a lot of time after chillin in the nowhere i time out, like idletimeout i think.

**Comment by johnfg12** [comment]
are u running the server and client on the same pc?

**Comment by nidico100** [comment]
yeah, i tried it on the same pc

**Comment by johnfg12** [comment]
could you try downloading from https://github.com/MyM-ModpackTeam/GalacticScience/releases

**Comment by nidico100** [comment]
i will try it now :)

**Comment by nidico100** [comment]
still the same
![2016-04-10_17 05 35](https://cloud.githubusercontent.com/assets/11612223/14411075/75621d04-ff3e-11e5-8445-f61a416482f5.png)

**Comment by johnfg12** [comment]
how are u floating?

**Comment by nidico100** [comment]
i'm standing on a block, i feel the hitboxes of the blocks, but i can't see them, I really don't understand why that happens

**Comment by johnfg12** [comment]
do u have optifine installed?

**Comment by nidico100** [comment]
nope

**Comment by nidico100** [comment]
complete clean gs

**Comment by johnfg12** [comment]
could u try a diffrent version see if that helps

**Comment by nidico100** [comment]
i tried 1.5.8 and it didn't change

**Comment by Bachuey** [comment]
Having the same issue with 1.5.9. Running the server on the same PC as the client works fine, but running on a Creeperhost server is having this issue as described above.

**Comment by nidico100** [comment]
if i run it on nitrado.net server it works, something creates this issue, but i can't figure it out..

**Comment by johnfg12** [comment]
could u upload the logs please

**Comment by nidico100** [comment]
don't have them anymore, deleted it

**Comment by drz2k** [comment]
1 month old/no logs/no further report - closing.
