### ISSUE TITLE
Getting back after dying

### ISSUE THREAD

**Issue by svschouw** [MyM-ModpackTeam/GalacticScience#117]
When you die, you really seem to have a problem, especially on another planet. I finally got my rocket and I went to mercury. Turns out, mercury is pretty barren and I didn't bring anything to help me get back (should I? maybe the quest book should mention that?). But oh well, lesson learned, let me just die and try that again. Since I'm dying anyway, might as well adventure a bit. I don't have anything really important on me, so I don't have to worry about my gravestone. So I venture off a bit, dig a deep hole and get killed by mobs in a big dark cave.

But I didn't spawn back on the moon, but at the lander, without gear. The quest book had a quest to give basic gear back, but I have no quest book. And my gravestone is so far off, I can't get to that before dying. But even if I could, I have no way to go back to the moon. So is really my only option to start a new world? Seems a little too hardcore.

(For the record, I'm playing 1.5.9 from the FTB launcher)

**Comment by drz2k** [comment]
Thats why most people bring power+rf teleporter and make an outpost first ;)

You can always enable cheats on lan and /cofh tpx back to moon ..

**Comment by svschouw** [comment]
Thanks for your answer. That saved me from having to restart from scratch.

But if that is your answer, that basically means that this modpack isn't suitable for new galacticraft players. I have no idea how to make a teleporter, nor how to bring portable power with me, nor does it warn you anywhere.

That said, I still think it's a big problem that you have to go through creative mode in order to recover from death. Kindof defeats the purpose of it being a non-hardcore map. It even has a quest you can only complete by dying.
