### ISSUE TITLE
Modular systems crusher craftable

### ISSUE THREAD

**Issue by drz2k** [MyM-ModpackTeam/GalacticScience#118]
https://mineyourmind.net/forum/threads/tipps-and-tricks.8627/page-2#post-112234

This is not intended. The crusher recipe was blocked/disabled in the past.

**Comment by Slind14** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/commit/4dc0564070b8efcae5aae96725f72a0f49892dc4
