### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by SkeletonKing051** [MyM-ModpackTeam/GalacticScience#119]
For some reason, without changing anything (as far as I know), the game simply would not run. Other packs will run on the same FTB Launcher.

Log: http://paste.feed-the-beast.com/view/raw/f0d848e4

**Comment by Bennyboy1695** [comment]
Loading the ModularSystems furnace seems to be what's causing the crash. Try re-installing the pack and if that doesn't work delete the folder its stored in and do a fresh install of the pack. Make sure to back up any worlds before deleting anything if your have any.

**Comment by SkeletonKing051** [comment]
Force updating still crashed (Log: http://paste.feed-the-beast.com/view/raw/7b65c4eb). Then I deleted the folder (backing up my world) and it loaded up. But when I started my world I crashed and got this log: http://paste.feed-the-beast.com/view/raw/169f72d4

**Comment by Bennyboy1695** [comment]
thats a hqm crash, you'll need to delete the hqm file in the world folder to fix it. But doing that will reset your questbook progress

**Comment by SkeletonKing051** [comment]
Ok so game loads, world loads but HQM Questing is disabled and I am not allowed to use the command to re-enable it. (Log: http://paste.feed-the-beast.com/view/raw/157e6b7a)

**Comment by Sir-Will** [comment]
Click Open To Lan and enable cheats then you can run the comment

**Comment by SkeletonKing051** [comment]
Ok questing is enabled but hardcore mode was enabled as well and I don't know how to turn it off

**Comment by Sir-Will** [comment]
You have to delete the file again and run /hqm quest then.
