### ISSUE TITLE
textures??

### ISSUE THREAD

**Issue by maddawwwggg302** [MyM-ModpackTeam/GalacticScience#12]
Games is missing textures for some vanilla items as well as some of the super massive tech, solar flux, Dalek and jabba mods. instead of appropriate textures i am receiving Black boxes or just empty air

**Comment by Slind14** [comment]
This seems to be on your end. Please try reinstalling the pack and updating the graphics driver.

**Comment by maddawwwggg302** [comment]
I tried reinstalling the pack however no changes were made

**Comment by SirWilli** [comment]
Can you post some screenshots of it and tell us which items?

**Comment by maddawwwggg302** [comment]
![image](https://cloud.githubusercontent.com/assets/14356833/9982024/f5e9710e-5f9b-11e5-8adb-9f93e1e5a5c0.png)

**Comment by maddawwwggg302** [comment]
that was what i was experiencing however it seems i have fixed the issue

**Comment by maddawwwggg302** [comment]
For anyone with a similar issue as this you should try to go to the resource packs tab in the options menu and click done. this fixed the issue for me

**Comment by SirWilli** [comment]
Great that you got it working
