### ISSUE TITLE
Massive Block Lag caused by Imaginary Time Block

### ISSUE THREAD

**Issue by Zeldinator** [MyM-ModpackTeam/GalacticScience#121]
As the title suggests, when activating the Imaginary Time Block from Quantum Flux to "power" my treefarm, the SP-Server starts to lag BADLY, taking around 3000µs (Opis) to update... Is this "normal" behavior or a bug of my instance?

**Comment by drz2k** [comment]
The block increases tick rate largly. If your hardware cant handle the extra-ticks, it will lag ofc...
