### ISSUE TITLE
Game crashes randomly in single player with no idea what happened

### ISSUE THREAD

**Issue by The1bishop** [MyM-ModpackTeam/GalacticScience#122]
> 
[hs_err_pid5256.zip](https://github.com/MyM-ModpackTeam/GalacticScience/files/233153/hs_err_pid5256.zip)

**Comment by Slind14** [comment]
You will need to remove the modular systems auto crafting station with mcedit.

**Comment by RoadCrosser1** [comment]
When i join my singleplayer world it crashes and says Server Closed 
How do i fix this ?
i worked hard on this world and i don't want to lose it

**Comment by drz2k** [comment]
Well after a month he figured out or gave up, closing.
