### ISSUE TITLE
Server Closed in SinglePlayer ?

### ISSUE THREAD

**Issue by RoadCrosser1** [MyM-ModpackTeam/GalacticScience#123]
Can someone help me fix this because i don't want to begin again.
I love this modpack, its my favorite.

When i start my world up, i join, them it closes itselfs and says Server Closed
I really don't know what to do 
Pls Help
PasteBin Crash-Report
http://pastebin.com/HpFDPqCa

**Comment by Sir-Will** [comment]
Please post your crash report.

**Comment by RoadCrosser1** [comment]
how do i report ?

**Comment by RoadCrosser1** [comment]
hello ?

**Comment by RoadCrosser1** [comment]
Can Clanteen help me ?

**Comment by Sir-Will** [comment]
Please stop to spam message and just wait.

See www.mym.li/crash on how to get the crash report

**Comment by RoadCrosser1** [comment]
Here's my pastebin
http://pastebin.com/HpFDPqCa

**Comment by Slind14** [comment]
You will have to remove the block on the moon at 17,69,199 with mcedit.

**Comment by RoadCrosser1** [comment]
how to get mcedit for Galactic Science ?

**Comment by Slind14** [comment]
You will need to show some self initiative after all this is an issue tracker not support channel

**Comment by RoadCrosser1** [comment]
thx

**Comment by RoadCrosser1** [comment]
it works :D! thank u very very much !
