### ISSUE TITLE
Offline spawn

### ISSUE THREAD

**Issue by Loikar** [MyM-ModpackTeam/GalacticScience#127]
So I got this modpack and first it gives me a cannot find ex nihilo mod, which is easy to find. But now whenever I try to start a world it spawns me out of world and I immediately die. This has happened every time I make a new world in this modpack

**Comment by drz2k** [comment]
If it already failed to install EN correctly you are probably missing out more like lockdown. 

Redownload/Force update/change launcher. The basic stuff.

**Comment by Loikar** [comment]
Okay, first off I've never used a modpack before and probably don't know what I'm doing.
So I redownloaded and the new rar file has the exact same contents of the first one, neither including ex nihilo. I'm assuming when you said force update you mean to extract the new file and replace all, which I did and nothing changed. Not sure what you mean by change launcher, though I tried diffferent forge versions.
Also, I downloaded tweaks for Galactic Science, and now it's spawning me on the moon

**Comment by Sir-Will** [comment]
Which launcher are you using?

**Comment by drz2k** [comment]
It sounds he isnt using a launcher at all.
https://mineyourmind.net/join-us.html
Get the mym launcher, it will install everything needed for you. Curse or FTB as alternative

**Comment by Loikar** [comment]
Alright, thanks it's working now, didn't know there were other launchers than the default mojang one. Also didn't know you're supposed to start on the moon for this modpack :P

**Comment by Sir-Will** [comment]
From where did you even get a .rar file we only provide .zip
