### ISSUE TITLE
modular cores/blöcks are not in nei and has no crafting rezepie,

### ISSUE THREAD

**Issue by TOBAS01** [MyM-ModpackTeam/GalacticScience#128]
i play galactic science now for 2 days and lookt very much youtubers but i cant make a modular crusher core.  I serched in nei and in the creative mode in creative is it but it does not have a rezept.
if someone now´s whats on pls comment.
thx

**Comment by Sir-Will** [comment]
It's disabled. It was never intended to be enabled.

**Comment by TOBAS01** [comment]
ok thx
