### ISSUE TITLE
Issue with B*Space sorting barrels with void upgrade.

### ISSUE THREAD

**Issue by jerbearx** [MyM-ModpackTeam/GalacticScience#133]
I'm having a problem with B*Space sorting barrels after the last update. I have barrels set up with B*Space upgrades, several storage upgrades, and void upgrades. The void upgrades no longer seem to work in this situation. Void upgrades are working in the sorting barrels that are not B*Spaced.

See https://github.com/Dynious/RefinedRelocation/issues/319 which explains the problem perfectly.

**Comment by Sir-Will** [comment]
We didn't update any mod except tardis and darkcore.

**Comment by jerbearx** [comment]
No longer an issue.
