### ISSUE TITLE
Can't load world backup

### ISSUE THREAD

**Issue by mReigl** [MyM-ModpackTeam/GalacticScience#135]
I've just experienced a computer crash while playing. Now the modpack crashes everytime during startup (launching from FTB-launcher). A reinstall fixed the pack but the worlds that I pasted in from the old directory are not appearing in the world selection screen.
So I need help with either getting the crashed version back running or the new version accepting the worlds.
Here's my crashlog: http://paste.feed-the-beast.com/view/8c7334d2

**Comment by Sir-Will** [comment]
Please replace your level.dat with one from the templates.
