### ISSUE TITLE
won't even open

### ISSUE THREAD

**Issue by joeyyellow2005** [MyM-ModpackTeam/GalacticScience#138]
I click launch, and then it just sits there with the app open, but no window. I reinstalled it and nothing happened. any ideas?!?!? PLZ HELP!

**Comment by joeyyellow2005** [comment]
nvm it just takes 10 minutes to open

**Comment by Sir-Will** [comment]
You might need to increase your RAM.

**Comment by joeyyellow2005** [comment]
ok thx

**Comment by joeyyellow2005** [comment]
it isn't slow when I play it, though, it just takes a long time for the window to actually work

**Comment by joeyyellow2005** [comment]
ps ram of my computer or how much fab can use?

**Comment by joeyyellow2005** [comment]
ftb not fab

**Comment by Sir-Will** [comment]
How much minecraft can use.

**Comment by joeyyellow2005** [comment]
i have 8gb memory on  menu. is that ram? how much should I increase it to? (sorry to bother you)

**Comment by joeyyellow2005** [comment]
thx in advance

**Comment by Sir-Will** [comment]
3-4 GB

**Comment by joeyyellow2005** [comment]
k

**Comment by joeyyellow2005** [comment]
i have it on 5 out of 8gb of RAM. it worked perfectly.

**Comment by Sir-Will** [comment]
I wouldn't go above 4

**Comment by joeyyellow2005** [comment]
ok but I have 8gb ram on my comp.

**Comment by Sir-Will** [comment]
Check http://vazkii.us/uncategorized/a-semi-technical-explanation-of-why-you-shouldnt-allocate-too-much-ram-to-minecraft/ ;)

**Comment by joeyyellow2005** [comment]
k
