### ISSUE TITLE
Metal Furnace (nuclear craft) doesn't burn hydrogen

### ISSUE THREAD

**Issue by davidma7685** [MyM-ModpackTeam/GalacticScience#139]
I'm not sure if this is a Galactic Science issue or a nuclear craft issue, but the Metal Furnace from Nuclear Craft doesn't burn hydrogen like other devices that use solid fuel do. It will burn Carbon, oddly enough, but not hydrogen.

**Comment by Sir-Will** [comment]
Issue will be fixed in 1.6.0
