### ISSUE TITLE
Can't Connect To Server Without Crashing

### ISSUE THREAD

**Issue by supergojeta** [MyM-ModpackTeam/GalacticScience#14]
Everytime i go to join the server after a long waiting for the game to load, the game crashes and a small set of words pops up at the bottom of the console and i cant get it to fix, so if someone could please update this and fix this error that would be nice.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Unity-Complete-1.1.0.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[16:45:16] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Supergojeta\AppData\Roaming\.mineyourmind\instances\MyM-GalacticScience\minecraft\crash-reports\crash-2015-09-20_16.45.16-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process ended with code: -1

**Comment by SirWilli** [comment]
Can you post your crash report via https://gist.github.com here, you can find it at `C:\Users\Supergojeta\AppData\Roaming.mineyourmind\instances\MyM-GalacticScience\minecraft\crash-reports\crash-2015-09-20_16.45.16-client.txt`

**Comment by supergojeta** [comment]
Ok i used that but it didnt show me a file, it said it couldnt find it, any short route to before i find it?

**Comment by SirWilli** [comment]
You can check this page too: www.mym.li/crash

**Comment by supergojeta** [comment]
Ok, Thank you

**Comment by supergojeta** [comment]
as you can see from the actual crash log, there doesnt look to be a source.
but me and my friend chri630 think it was something with our star productivity
and it wasnt. but can you go check his island and find out if its something there, or see if im just being crashed by a server command.

**Comment by SirWilli** [comment]
Can you post the link to your crash report else I can't see it

**Comment by supergojeta** [comment]
https://gist.github.com/supergojeta/1d0abe528e30dd82da13

**Comment by SirWilli** [comment]
Okay, you are in a dimension which doesn't exist. Do you play on our server? (MyM) If yes, whats your in game name?

**Comment by supergojeta** [comment]
I was on the moon when it crashed me the first time

**Comment by supergojeta** [comment]
but my ingame name is The_Editor

**Comment by supergojeta** [comment]
wait now my friend Chri630 is having the problem im having

**Comment by SirWilli** [comment]
I teleported you to the spawn, you should be able to login now.

It would be great if you can create a thread on our forum the next time for issues on our server. As this issue tracker is mainly used for bugs in singleplayer and our staff team doesn't look here.

Edit: I teleport your friend to the spawn too.

**Comment by supergojeta** [comment]
it fixed it
we have to fix our island

**Comment by supergojeta** [comment]
Willi it happened again. i need your helpa gain
