### ISSUE TITLE
When clicking statistics game crash.

### ISSUE THREAD

**Issue by dzwon21** [MyM-ModpackTeam/GalacticScience#141]
Hello, when clicking  statistics on pause menu game window gets grey and then crashes.
Crash logs:
[crash-2016-07-08_12.16.05-client.txt](https://github.com/MyM-ModpackTeam/GalacticScience/files/354020/crash-2016-07-08_12.16.05-client.txt)
[crash-2016-07-08_12.25.48-client.txt](https://github.com/MyM-ModpackTeam/GalacticScience/files/354021/crash-2016-07-08_12.25.48-client.txt)
(Sorry for bad English).

**Comment by Sir-Will** [comment]
No big issue.
