### ISSUE TITLE
Galactic Science won't open.

### ISSUE THREAD

**Issue by wsanders99** [MyM-ModpackTeam/GalacticScience#143]
I've read through the other issues regarding the pack not launching and followed through their listed solutions, be it reinstalling the modpack, removing the ModularSystems folder, etc. The pack is still crashing after it hits step 5 out of 7 on the loading screen.

Here is the crash log.
https://gist.github.com/wsanders99/e637a61b4bfa00b87036cb8ed54f623d

**Comment by Sir-Will** [comment]
Remove the ModularSystems configs or remove the mod.

**Comment by wsanders99** [comment]
I guess I'll just remove the mod. Removing the configs didn't work. I don't understand why it wouldn't work now, though, since it was working for the past three days.

**Comment by Sir-Will** [comment]
Oh, just got the same issue on our server. Looks like the version check of the mod is causing it and there is no option to turn that off, so the only way is to remove the mod.
