### ISSUE TITLE
Crashing in last phase because of Chisel

### ISSUE THREAD

**Issue by THE-MegaMan** [MyM-ModpackTeam/GalacticScience#144]
The modpack always crashes at loading in the last part, got the newest version of the FTB launcher and Modular Systems is not active. Java produces a segfault, the log of it is also included in the gist below.
Updated to Oracle JDK 1.8, didn't help.
**Here's the link to the crashlog:**
https://gist.github.com/THE-MegaMan/b3d7bb66ae12d6af103ed17efef0944e

**Update:** Chisel generated the crash at loading the texture for chisel:factoy/wireframewhite

**Comment by kindlich** [comment]
Do you have any kind of texture-Pack installed?

**Comment by THE-MegaMan** [comment]
No, just ran the original modpack with FTB launcher. But I've got OpenJDK 1.7 and a 32 bit PC. Could that be the problem?

**Comment by kindlich** [comment]
Well, most mods are designed for Java 8 these days...

Try using the [jdk 1.8.0](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Comment by THE-MegaMan** [comment]
I know, got slow internet, but it's worth a try.

**Comment by THE-MegaMan** [comment]
Could the reason be that the RF API is included in 2 different mods? I updated to Oracle JDK 1.8, but the error still occurs...

**Comment by kindlich** [comment]
1st: did you set your game to the new java version xP

2nd: Your crash is about registering the texture of a chisel block, so the RF API shouldn't have anything to do with it...

You could try to forcefully override the texture maybe?

**Comment by THE-MegaMan** [comment]
1st: The new java version is standard so it should be no problem except FTB launcher uses the absolute path
2nd Oops. Somewhere in the crash part is some text about the RF API which made it happen maybe.

How to forcefully override?

**Comment by kindlich** [comment]
Ok, first you check if it runs fine without the chisel mod installed
If it does you should first try to redownload the chisel mod...

**Comment by THE-MegaMan** [comment]
Ok, I'm gonna try out soon

**Comment by THE-MegaMan** [comment]
It seems like the factory folder is corrupted. If I try to open it with my archive program, it just quits.

**Comment by kindlich** [comment]
Ok, if oyu say your factory folder inside your .jar is corrupted, then jsut re-download the chisel.jar

**Comment by THE-MegaMan** [comment]
Used my redownloaded .jar. They have both the same md5sum and the error also appears with that one. 
I just created an issue about the same problem on the Chisel project. Any other tips what to do? Chisel isn't necessary, but it would be pretty cool.

**Comment by Sir-Will** [comment]
Did you reinstall the modpack yet?

**Comment by Sir-Will** [comment]
If you are missing blocks like you said in #145 then you probably have a corrupt/incomplete modpack download.

**Comment by THE-MegaMan** [comment]
Huh. That could be the problem. I see, the problem isn't Chisel (the same jar worked fine on self-installed Forge), but the "collaboration" of the other mods with Chisel. I reinstall now.

**Comment by THE-MegaMan** [comment]
I redownloaded wit FTB, but the crash is exactly the same. Are there mods (except Chisel) which aren't needed and need many textures?

**Comment by Sir-Will** [comment]
Can you try with MyM-Launcher?

**Comment by THE-MegaMan** [comment]
I'm trying it, I set the RAM a bit higher, maybe that could be useful.

**Comment by THE-MegaMan** [comment]
I tried it, same issue, but on an other texture. Anything I can do against it without disabling Chisel?

**Comment by Sir-Will** [comment]
Can you upload the log?

**Comment by THE-MegaMan** [comment]
Do you mean in the launcher? I did, but if you mean on Gist, here is the crash:
https://gist.github.com/THE-MegaMan/1c6ac8fe4ccc5c2a73a1fc53dc06bf65
Sorry, it was exactly on the same texture.

**Comment by Sir-Will** [comment]
I mean the full client log, not crash report.

**Comment by THE-MegaMan** [comment]
I'm not sure if it's enough, but I uploaded it in the launcher console with that button. I'm sorry I closed the launcher already, but if it's needed I can reproduce the error.

**Comment by Sir-Will** [comment]
Then post the link of that upload.

**Comment by THE-MegaMan** [comment]
OK, I'm gonna reproduce now, will take ~5 min.

**Comment by THE-MegaMan** [comment]
So here is the link to the full client log:
https://gist.github.com/THE-MegaMan/1f6ba3ca13f25dcafecf9328b1d424ca

**Comment by Sir-Will** [comment]
How much ram do you have allocated?

**Comment by THE-MegaMan** [comment]
1280 MB max

**Comment by Sir-Will** [comment]
Hm, no idea what the issue is on your side then. It works fine for me with 1.25GB

**Comment by THE-MegaMan** [comment]
Like I said already, it could be my GPU. And I'm using 32-bit Linux (Debian Jessie), could that be the reason?

**Comment by Sir-Will** [comment]
The crash report doesn't say much unfortunately. This crash happens normally if there is not enough memory to cache the textures.

**Comment by THE-MegaMan** [comment]
I know, I've got a built-in GPU on my computer, which is the opposite of powerful...

**Comment by Sir-Will** [comment]
Might want to check if it is running over the CPU or GPU if you have an hybrid GPU.

**Comment by THE-MegaMan** [comment]
Nope, not hybrid, ONLY built-in...annoying and slow...

**Comment by Sir-Will** [comment]
Does it run if you remove all mods except chisel?

**Comment by THE-MegaMan** [comment]
You mean if I use only Chisel or if I use everything BUT Chisel? Both work, Chisel works at least in my Forge installation of some other mods.

**Comment by Sir-Will** [comment]
Ok, I'm out of ideas then.

**Comment by THE-MegaMan** [comment]
Ok, maybe it's just my stupid GPU. (No offense, GPU!)
