### ISSUE TITLE
Map not really usable anymore

### ISSUE THREAD

**Issue by THE-MegaMan** [MyM-ModpackTeam/GalacticScience#145]
Since the new update without ModularSystems, the map is kind of corrupted. The floor and the walls of your base are gone and it's pretty hard to do most things now.

**Comment by Sir-Will** [comment]
Looks fine:
![](http://i.imgur.com/A9DjZZ2.jpg)
![](http://i.imgur.com/MzU1T4J.jpg)

**Comment by THE-MegaMan** [comment]
The second map is fine, but the first map seems to need the ModularSystems blocks. Should I install ModularSystems even though it seems to be broken or are there other ways?

**Comment by Sir-Will** [comment]
No, there are not any modular systems in the map. Please reinstall the modpack and if the issue still exists post a screenshot of it.

**Comment by THE-MegaMan** [comment]
Okay.

**Comment by THE-MegaMan** [comment]
Are there chiseled blocks in the map?

**Comment by Sir-Will** [comment]
Yes.

**Comment by THE-MegaMan** [comment]
Oh. I had to disable Chisel mod because it caused the crash. XD. Now I'm closing really.
