### ISSUE TITLE
pls help, trasparent blocks

### ISSUE THREAD

**Issue by ArcherV3** [MyM-ModpackTeam/GalacticScience#147]
please help me

since the last update when I break a block, all blocks become transparent.
![trasparent block](https://cloud.githubusercontent.com/assets/22558580/19013328/ea37d142-87cd-11e6-9e5f-2dd4ecfd65e5.png)

could you help with this problem? 

regards

**Comment by Sir-Will** [comment]
Can you post your client log with www.pastebin.com?
Do you have any extra mods installed?

**Comment by ArcherV3** [comment]
solved, more or less. i've applied 3 downgrade and with 1.5 the pack work properly.

thank you for your interest
