### ISSUE TITLE
read it and solve it ..

### ISSUE THREAD

**Issue by DeMoGa** [MyM-ModpackTeam/GalacticScience#149]

**Comment by Sir-Will** [comment]
What?

**Comment by DeMoGa** [comment]
sorry i mean i dnt see NO INFORMATION ABOUT ITEMS WHEN I MOVE CURSOR TO RESPECTIV ITEM

**Comment by DeMoGa** [comment]
Why site writed life.. wtf wrong auto correction ..

**Comment by Sir-Will** [comment]
I still don't understand what do you mean? What info?

**Comment by DeMoGa** [comment]
http://imgur.com/a/CtXEn
how to explain better when i move my mouse cursor on a specific item i see info about it and from wha tmod it is

**Comment by DeMoGa** [comment]
hope u understand what i want to tell you..

**Comment by Sir-Will** [comment]
You seem to have waila disabled or the mod not installed.

**Comment by DeMoGa** [comment]
in my laguage pls i dnt know how to activate it... after 3 mounths i got this amazing mod of mc but i didnt get it legally :(

**Comment by DeMoGa** [comment]
http://imgur.com/a/Hq6xc

**Comment by Sir-Will** [comment]
Press Numpad 0 and check if it is disabled there.

**Comment by DeMoGa** [comment]
thank u god of mc galactic

**Comment by DeMoGa** [comment]
there i see and mini map?

**Comment by Sir-Will** [comment]
Galactic Science doesn't have a minimap in the pack. You would need to install on yourself if you really want one.

**Comment by DeMoGa** [comment]
no better not i dnt want broke it anyway again thanks
