### ISSUE TITLE
Need Teleport to Spawn

### ISSUE THREAD

**Issue by supergojeta** [MyM-ModpackTeam/GalacticScience#15]
Last time it happened my items disappeared and this time it happened again and i dont know how to fix it so im just gonna leave this here hoping someone can help me, im not sure how to make a thread on something other than the single player thread because i cant find the link, my username in the game is The_Editor and i play Galactic Science.

**Comment by SirWilli** [comment]
done, you can find the forum here: https://mineyourmind.net/forum/
