### ISSUE TITLE
Crash initializing game

### ISSUE THREAD

**Issue by TexasShadowKat** [MyM-ModpackTeam/GalacticScience#152]
I'm not exactly good with coding and such, so I was hoping to get some help.
Crash report [here](http://pastebin.com/RU4uGsQq)

**Comment by Sir-Will** [comment]
You are in a not loaded world. Move your location to DIM28.

**Comment by TexasShadowKat** [comment]
I'm sorry, could you tell me how to do that...?

**Comment by Sir-Will** [comment]
Download NBTExplorer, open your playerfile with it (can be found in your saves/<world>/playerdata) and edit the "dimension" entry.
Make sure to backup your player file as you might be stuck in the ground depending on the coordinates.

**Comment by TexasShadowKat** [comment]
Another crash log... http://pastebin.com/5Gi7UYzX

**Comment by Sir-Will** [comment]
That's the same crash.

**Comment by TexasShadowKat** [comment]
I'm sorry. It didn't change anything then.

**Comment by Sir-Will** [comment]
Can you reopen the player file and post a screenshot?

**Comment by TexasShadowKat** [comment]
![screenshot 2016-11-14 12 40 52](https://cloud.githubusercontent.com/assets/23459806/20277818/c674beca-aa67-11e6-8976-b2c94f2e07c6.png)

**Comment by Sir-Will** [comment]
Try deleting DIM2 folder in saves.

**Comment by TexasShadowKat** [comment]
No change.

**Comment by Sir-Will** [comment]
Disable RandomThings mod then, the mod is trying to create a world which already exists.
