### ISSUE TITLE
Automatic Sieving

### ISSUE THREAD

**Issue by TexasShadowKat** [MyM-ModpackTeam/GalacticScience#153]
So, while attempting to create the auto sieve, I found that the recipe apparently doesn't exist. Is this something planned to be fixed, since it's part of the quest book? I keep going into NEI and repeatedly clicking at it to find a recipe, but I'm given nothing. As far as I can tell, all other recipes are fine.

**Comment by Sir-Will** [comment]
Can't reproduce in 1.6.4, so should be fixed in that update.
