### ISSUE TITLE
Observatory Map

### ISSUE THREAD

**Issue by MBfromOK** [MyM-ModpackTeam/GalacticScience#154]
Tested in 1.6.3, 1.5x, and 1.4.x:
I use the Curse loader and have found that the (default) Observatory map template contains 3 (spawned) entities, so when spawning & creating a map with this template you get greeted by 3 random mobs even though the room is lit. If you are setting up teams, customizing Galacticraft colors and logos, or looking through the 2 spawn books this can be quite devastating especially when you have no weapon and use up valuable energy to try and kill them, or just die after a disturbing hiss.

Love the pack, this is my 3rd restart, I started playing in 1.4, but lost the save due to ye olde Modular Storage & Ex Astris changes.  Glad to see that the pack is being maintained / updated!

**Comment by Sir-Will** [comment]
Unable to reproduce this.
