### ISSUE TITLE
Cursed Earth Does not Spawn Mobs

### ISSUE THREAD

**Issue by wyndman** [MyM-ModpackTeam/GalacticScience#155]
Version 1.64 Galactic Science, When cursed earth is used in a dark room it fails to spawn monsters. Tested on the MyM server, and in single player with the results being the same.

**Comment by Invortrex** [comment]
On the MyM server, I have a small room that has a 2x5 cursed earth patch surrounded by walls and roofed and it does spawn mobs for me, however, I have had it up and running, chunk loaded for the past 3 days and the only mob drops that I do seem to get are zombie related.

**Comment by Sir-Will** [comment]
Unable to reproduce this.
