### ISSUE TITLE
RF Tools: Endergenic Generators

### ISSUE THREAD

**Issue by MBfromOK** [MyM-ModpackTeam/GalacticScience#156]
Maybe an intended feature/bug, maybe an oops...

RFTools includes the Endergenic generator, a complicated power generation system that can (if you make the effort) produce up to 16k RF/t... I had never used it or heard about it, saw it in NEI and looked it up on the wiki.  After trying 9 different builds I was unable to get it working, so, I went online seeking help... I tried to copy ToddytheBody - (https://youtu.be/eMOmowThBLE and https://youtu.be/vcNIu9OCiDI), and LandStryder's  - (https://youtu.be/mimoszRgYRI) setups... neither work.  Failing there I utilized the power of reddit and forums to recreate others' working build, all with the same result.

I referred to 1.9 and 1.10 videos from McJty and Direwolf20 to try and learn if I was doing something wrong, I can get it to fire 1-2 times, and produce a small amount of power due to that, but can't get it to function past the 2nd generator (complete the circuit).  I tried using EnderIO conduits for everything after watching ToddytheBody discuss his setup, that didn't work.

I have built excel spreadsheets, played with timings, duplicated my Galactic Science save, made it creative, and built 16 chunk centered variations of the generator setup.  Most of the people that use this say that it functions with the Programmable Rednet Controller, going to unlock the pack, add just the PRC and wire and try that next... Before I do, is this a bug, intentional, or removed with next update (now that I have pointed out it is an option)?

FWIW: My path to this setup was provided by an Enderman spawn egg in a loot bag allowing me to create an Enderman powered spawner by trapping it in a soul vial.

Will update this if PRC fixes it...

Thanks!!

Micah

**Comment by Sir-Will** [comment]
There will be most likely no new modpack updates.
