### ISSUE TITLE
Pack Feedback / Request

### ISSUE THREAD

**Issue by MBfromOK** [MyM-ModpackTeam/GalacticScience#157]
Several YouTubers have played this pack, but none have completed it... I am excited to see what is still in the pack, although I must say my excitement for a tech based pack with an alternative starting path almost died when I saw / heard that Blood magic is in here.. Adding magic to this pack makes it the same as every other magi-tech pack out there other than the customized start and restricted progression.  Crash Landing & The Material Energy series were amazing because they offered a "futuristic" Minecraft experience without magic and focused / capitalized on using technology for pack progression.  Utilizing the Galacticraft mechanics you have the possibility to create a grand adventure through the stars with each planet offering a piece / key of the final destination without involving magic.. I understand that you have put a lot of time into this and I value your time... This has been great fun so far, I do home that you will consider removing it and adding progression using another route?

**Comment by drz2k** [comment]
Quite a few have completed it. Streamers and players on the mym server. Until you "completed" the pack you dont have access to blood magic and it serves a purpose - you will find out after completing the stargate ;)
