### ISSUE TITLE
Crash Report Since New Version

### ISSUE THREAD

**Issue by Princebeaver** [MyM-ModpackTeam/GalacticScience#159]
http://pastebin.com/zRAjdDyv This is a link to my crash report. Game also crashed when I clicked on the Stats button. Please help me. I have no idea if this is the right place to post this but this is where I put it. Thanks in advance.

**Comment by Sir-Will** [comment]
Please verify you have OpenComputers in your mods folder.

**Comment by Princebeaver** [comment]
Yes I do Indeed have open computers in my mods folder. I had the manual on the world that I played before the bug.

**Comment by Sir-Will** [comment]
When exactly does it crash?
