### ISSUE TITLE
Dimensional chest

### ISSUE THREAD

**Issue by henryauyong** [MyM-ModpackTeam/GalacticScience#160]
i put my tier 3 rocket in a dimensional chest while the server is restarting.(i am opening the gui.)

when i rejoined the server, my rocket disappeared.

can i get back my rocket?

my username is :Henry_AuYong

to prove that i got the rocket:

http://i.imgur.com/Oie1Pss.jpg

http://i.imgur.com/xE17EJC.jpg

**Comment by kindlich** [comment]
I am pretty sure that you are encountering this issue on the MyM-Server, aren't you?

The github issue tracker is only for issues relating the pack itself like recipe bugs or game-crashing issues...
To contact a moderator on the MyM-Network, submit a ticket using "/ticket create" ingame

**Comment by drz2k** [comment]
What kindlich said :)
