### ISSUE TITLE
Quest books wont open 

### ISSUE THREAD

**Issue by MeasuredStar673** [MyM-ModpackTeam/GalacticScience#161]
im an experienced player and the quest books wont open on the public server and its everone not just me 
send somone on to fix it asap

**Comment by kindlich** [comment]
I am pretty sure that you are encountering this issue on the MyM-Server, aren't you?

The github issue tracker is only for issues relating the pack itself like recipe bugs or game-crashing issues...
To contact a moderator on the MyM-Network, submit a ticket using "/ticket create" ingame or any other method like poking a moderator on the MyM TeamSpeak 3 Server or using the Support Slack/Discord Channel
