### ISSUE TITLE
slow please help if you can

### ISSUE THREAD

**Issue by Ajpatriot** [MyM-ModpackTeam/GalacticScience#166]
Everything for some reason is just really slow the title screen everything it won't keep up with my mouse it's al just so slow I want to give this modpack a chance but if no one can help fix it then I guess i will have to try something else

**Comment by NolanSyKinsley** [comment]
Logs are needed to help you.

**Comment by kindlich** [comment]
As Nolan said, we need some further information:
Operating System
OS Architecture
Java Version (also, using JDK, OR JRE)
Memory (RAM)
Memory assigned to Java

Or a log as it contains most of this information
For now, try lowering your graphics settings (e.g. View Distance, Rendering Methods etc.) or add a performance improving mod like Optifine/BetterFPS/Fastcraft and the likes
