### ISSUE TITLE
A Bug i can't craft

### ISSUE THREAD

**Issue by xlpskydiehdx** [MyM-ModpackTeam/GalacticScience#167]
Hallo at the moment i play your modpack GalacticScience its very nice but i have a problem i craft me a RR Pickaxe than the pickaxe is broken  now i want craft him again but the problem is it isn't work i have all the material but it isn't work (I play this Mod on Twitch launcher)

**Comment by Sir-Will** [comment]
Cannot Unable to reproduce this.
