### ISSUE TITLE
[Suggestion] Distribute Server-Specific Download

### ISSUE THREAD

**Issue by janagyjr** [MyM-ModpackTeam/GalacticScience#169]
Would it be possible to get server specific downloads for Galactic Science?

**Comment by Sir-Will** [comment]
There already is one: https://github.com/MyM-ModpackTeam/GalacticScience/releases/tag/1.6.4

**Comment by janagyjr** [comment]
There is no indication anywhere on Curse that it exists. Thank you.
![image](https://user-images.githubusercontent.com/23646259/29077686-431870ba-7c1e-11e7-9fbb-e273f55ece4a.png)

**Comment by Sir-Will** [comment]
I added a link to the file changelog and uploaded the server files there too (needs to approved by curse first).
