### ISSUE TITLE
Update Supermassive Tech for bug fixes.

### ISSUE THREAD

**Issue by NolanSyKinsley** [MyM-ModpackTeam/GalacticScience#17]
I ran into a crash when trying to max out a star formation and it turns out the modpack is using a really really old version, from before november of last year as the fix for the issue I encountered was fixed in this commit: https://github.com/tterrag1098/SuperMassiveTech/commit/ad7034a9f656db700d48a67ff10d50eaa58f8d24

There are lots more of bug fixes that came after that point as well.

**Comment by Slind14** [comment]
Thanks for the notice, we will make sure to test/include it in the next update.

**Comment by Slind14** [comment]
You could help us if you update it your self and report back how well the it is working (including the version used). Would save us some testing time. :)

**Comment by NolanSyKinsley** [comment]
Sure thing, should I attempt to bring all mods to current?

**Comment by Slind14** [comment]
I wouldn't many of the mods depend on others and if you update one it breaks 4 others. Especially with those where one of the others is not maintained atm and therefor you can't update at all. As the pack is feature complete know, we should focus on bug fixes only. Hence only considering mod updates if they fix major bugs.

**Comment by NolanSyKinsley** [comment]
Ok, got it updated after a bit of fiddling.

You need to add EnderCore-1.7.10-0.0.1.16_alpha then update to SuperMassiveTech-MC1.7.10-0.4.0-alpha-113, no other changes required and everything works as normal.

Note: There were changes to "star death" and I still don't know what exactly what those changes are, am looking into it though.

**Comment by NolanSyKinsley** [comment]
Oh god... Yea, IDK if you should update or not, if you do you will need a very strongly worded warning about star death....

It consumes the machine in an explosion that can damage nearby blocks and leaves a black hole in it's place. And if it just sits there it is fine.... But my curiosity got the better of me...

You can move the black hole by breaking it, so I moved it and I noticed when I threw an item in the WAILA tooltip showed the energy going up briefly... So I did what anyone would do... I threw a stack of cobble in to see what happens.... It's attraction grew verys tron and it started consuming the blocks around it and that gave it more energy and it got bigger and got to my wall of barrels and once it broke open those it consumed my entire station and everything I had.....


The energy drops quickly, but if it is fed more than it is dropping it grows and consumes everything... very dangerous....

**Comment by NolanSyKinsley** [comment]
Okay.. Second issue, the quests all have to be re done with the new stars data, otherwise they are spawned in with a life of 0 and they blow up the player creating a black hole. Slightly more work than I thought....
