### ISSUE TITLE
Slash Spawn Is Broke?

### ISSUE THREAD

**Issue by janagyjr** [MyM-ModpackTeam/GalacticScience#170]
I'm op on a GC server and our users discovered they could not use /spawn. It puts them under the world and they fall into the void. I did a /setworldspawn x y z and then did /spawn myself and still wound up falling out of the world (or would have had I not been in creative). Is this intentional? 

GC 1.6.4

Repeatable even in creative.

**Comment by Sir-Will** [comment]
Try something like this: https://minecraft.curseforge.com/projects/perfect-spawn

**Comment by drz2k** [comment]
If you want server features .... you need to install them ...

**Comment by janagyjr** [comment]
Considering /spawn is an FTB Lib/Utilities feature, they should be enabled by default. On no other 1.7.10 server that I play on that uses FTB Lib/Utilities do I have a problem.

I shouldn't need another mod for /spawn (or /home /sethome ).
