### ISSUE TITLE
Server locks up, not responding to commands, timing out players when trying to log in or in game.

### ISSUE THREAD

**Issue by martmists** [MyM-ModpackTeam/GalacticScience#173]

**Comment by martmists** [comment]
Note that this is our own server, not the official one

**Comment by Bennyboy1695** [comment]
Galactic Science can be quite a heavy resource using pack, you'll need to make sure its being allocated enough resources

**Comment by wyndman** [comment]
Could you post your console logs,  might give us something to work off of.

**Comment by martmists** [comment]
Console log last prints a server join and stops after that, I'll see if I can get one
