### ISSUE TITLE
crashing because of entity ticking (and player ?)

### ISSUE THREAD

**Issue by SkyKeeL** [MyM-ModpackTeam/GalacticScience#180]
first thanks you for reading this and trying to help second here's the crash

Hey i have a problem with a ticking entity the thing is i dont have the time to reconnect a /kill @e because it instantly crashes but when i put this command in the console of my server it says : you must specify wich player you want to perform this action on

what i was doing before the crash ? i was switching stuff in my inventory and i accidentaly dropped a star from super massiv tech which got aspirated by the star harvester and it crashed

here's the crash report: minecraft modpack galactic science ( 1.7.10)

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/23/18 1:51 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
at tterrag.supermassivetech.common.item.ItemStar.func_77663_a(ItemStar.java:56)
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:381)
at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311)
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:43)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:63)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at tterrag.supermassivetech.common.item.ItemStar.func_77663_a(ItemStar.java:56)
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:381)
at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311)
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:43)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:63)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)
Entity ID: 149
Entity Name: Sky_Keel
Entity's Exact location: -37.77, 55.62, 181.30
Entity's Block location: World: (-38,55,181), Chunk: (at 10,3,5 in -3,11; contains blocks -48,0,176 to -33,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [GCEntityClientPlayerMP['Sky_Keel'/149, l='MpServer', x=-37.77, y=55.62, z=181.30]]
Chunk stats: MultiplayerChunkCache: 5, 5
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (204,64,256), Chunk: (at 12,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 689142 game time, 121186 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 42 total; [EntityMeteor['Meteor'/263, l='MpServer', x=88.03, y=167.16, z=47.66], EntityMeteor['Meteor'/264, l='MpServer', x=72.69, y=206.16, z=322.16], EntityEvolvedSkeleton['Evolved Skeleton'/212, l='MpServer', x=17.50, y=65.00, z=258.50], EntityItemFrame['entity.ItemFrame.name'/150, l='MpServer', x=-38.06, y=62.50, z=185.50], EntityItemFrame['entity.ItemFrame.name'/151, l='MpServer', x=-42.50, y=61.50, z=188.94], EntityEvolvedZombie['Evolved Zombie'/152, l='MpServer', x=-42.53, y=60.00, z=201.19], EntityMeteor['Meteor'/280, l='MpServer', x=75.19, y=198.88, z=46.50], EntityEvolvedZombie['Evolved Zombie'/153, l='MpServer', x=-55.50, y=11.00, z=206.50], EntityMeteor['Meteor'/281, l='MpServer', x=96.97, y=140.59, z=303.91], EntityEvolvedZombie['Evolved Zombie'/154, l='MpServer', x=-75.84, y=25.00, z=184.50], EntityEvolvedSpider['Evolved Spider'/155, l='MpServer', x=-60.13, y=11.00, z=219.38], EntityEvolvedZombie['Evolved Zombie'/156, l='MpServer', x=-54.31, y=12.47, z=209.28], EntityEvolvedCreeper['Evolved Creeper'/157, l='MpServer', x=-75.50, y=24.00, z=174.50], EntityEvolvedSpider['Evolved Spider'/158, l='MpServer', x=-8.00, y=15.00, z=207.78], EntityEvolvedCreeper['Evolved Creeper'/159, l='MpServer', x=-6.84, y=15.00, z=202.47], EntityEvolvedZombie['Evolved Zombie'/160, l='MpServer', x=-11.50, y=17.00, z=196.50], EntityItem['item.item.chickenRaw'/161, l='MpServer', x=-10.19, y=16.13, z=198.16], EntityMeteor['Meteor'/289, l='MpServer', x=57.91, y=70.94, z=321.06], EntityEvolvedZombie['Evolved Zombie'/162, l='MpServer', x=-16.16, y=3.00, z=212.13], EntityMeteor['Meteor'/290, l='MpServer', x=96.44, y=206.88, z=219.09], EntityEvolvedSkeleton['Evolved Skeleton'/163, l='MpServer', x=-27.50, y=9.00, z=226.50], EntityEvolvedSkeleton['Evolved Skeleton'/164, l='MpServer', x=-22.53, y=8.72, z=229.50], EntityMeteor['Meteor'/292, l='MpServer', x=-96.16, y=167.75, z=47.03], EntityEvolvedZombie['Evolved Zombie'/165, l='MpServer', x=-8.50, y=13.00, z=233.50], EntityEvolvedZombie['Evolved Zombie'/166, l='MpServer', x=-55.50, y=18.00, z=249.50], EntityEvolvedSkeleton['Evolved Skeleton'/167, l='MpServer', x=-107.50, y=60.00, z=196.50], EntityEvolvedSkeleton['Evolved Skeleton'/168, l='MpServer', x=-61.50, y=6.00, z=114.50], EntityEvolvedZombie['Evolved Zombie'/169, l='MpServer', x=27.47, y=38.00, z=164.34], EntityEvolvedCreeper['Evolved Creeper'/170, l='MpServer', x=18.50, y=63.00, z=151.50], EntityEvolvedSpider['Evolved Spider'/171, l='MpServer', x=-83.50, y=65.00, z=253.50], EntityEvolvedCreeper['Evolved Creeper'/172, l='MpServer', x=-104.50, y=63.00, z=228.50], EntityEvolvedCreeper['Evolved Creeper'/173, l='MpServer', x=-101.50, y=63.00, z=227.50], EntityEvolvedSkeleton['Evolved Skeleton'/174, l='MpServer', x=16.50, y=65.00, z=143.50], EntityEvolvedSkeleton['Evolved Skeleton'/175, l='MpServer', x=36.50, y=36.00, z=179.50], EntityEvolvedZombie['Evolved Zombie'/179, l='MpServer', x=-50.50, y=14.00, z=261.50], GCEntityClientPlayerMP['Sky_Keel'/149, l='MpServer', x=-37.77, y=55.62, z=181.30], EntityEvolvedZombie['Evolved Zombie'/180, l='MpServer', x=-59.69, y=23.00, z=258.00], EntityEvolvedSpider['Evolved Spider'/183, l='MpServer', x=-114.13, y=64.00, z=159.44], EntityEvolvedZombie['Evolved Zombie'/188, l='MpServer', x=24.50, y=65.00, z=247.50], EntityEvolvedSkeleton['Evolved Skeleton'/189, l='MpServer', x=-86.50, y=65.00, z=258.50], EntityEvolvedCreeper['Evolved Creeper'/190, l='MpServer', x=-81.50, y=65.00, z=256.50], EntityEvolvedSpider['Evolved Spider'/191, l='MpServer', x=-87.50, y=13.00, z=103.50]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1056851176 bytes (1007 MB) / 1719140352 bytes (1639 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 85 mods loaded, 85 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHIJA Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHIJA CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
UCHIJA Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
UCHIJA NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
UCHIJA OpenComputers|Core{1.6.0.9} [OpenComputers (Core)] (minecraft.jar) 
UCHIJA OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
UCHIJA <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
UCHIJA GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
UCHIJA SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9-CUSTOM_1.jar) 
UCHIJA bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
UCHIJA Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
UCHIJA armourersWorkshop{1.7.10-0.42.4} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.42.4.jar) 
UCHIJA plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.42.4.jar) 
UCHIJA CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
UCHIJA AwesomeSauceCore{0.1.0} [AwesomeSauce Core] (AwesomeSauceCore-1.7.x-b52.jar) 
UCHIJA AwesomeSauceComponents{0.1.0} [AwesomeSauce Components] (AwesomeSauceCore-1.7.x-b52.jar) 
UCHIJA bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
UCHIJA betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
UCHIJA AWWayofTime{v1.3.3}
[Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
UCHIJA chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
UCHIJA CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
UCHIJA CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
UCHIJA thedalekmod{39.75} [The Dalek Mod] (Dalek_Mod_1710.jar) 
UCHIJA darkcore{0.41} [Dark Core] (darkcore-0.41-180.jar) 
UCHIJA ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
UCHIJA DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
UCHIJA dimstorage{1.3} [DimStorage] (DimStorage-1.7.2-1.3.jar) 
UCHIJA Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.12.0.jar) 
UCHIJA endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
UCHIJA Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
UCHIJA EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
UCHIJA exnihilo{1.38-53} [Ex Nihilo] (Ex-Nihilo-1.38-53.jar) 
UCHIJA exastrisrebirth{MC1.7.10-1.01-null} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar) 
UCHIJA ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
UCHIJA MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
UCHIJA FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
UCHIJA FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
UCHIJA GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
UCHIJA GalacticScience_Tweaks{1.4} [GalacticScience-Tweaks] (GalacticScience_Tweaks-1.5.jar) 
UCHIJA minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
UCHIJA advgenerators{0.9.20.123} [Advanced Generators] (generators-0.9.20.123-mc1.7.10.jar) 
UCHIJA GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
UCHIJA hardcoremapreset{2.2.0} [HardcoreMapReset] (HardCoreMapReset-2.2.0.jar) 
UCHIJA HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
UCHIJA inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
UCHIJA inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
UCHIJA IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
UCHIJA JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
UCHIJA launchgui{1.7.10-2.0-18} [LaunchGUI] (LaunchGui-1.7.10-2.0-18-client.jar) 
UCHIJA Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
UCHIJA modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
UCHIJA NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
UCHIJA Netherless{0.9.0} [Netherless] (Netherless-0.9.0.jar) 
UCHIJA NuclearCraft{1.9d} [NuclearCraft] (NuclearCraft-1.9d--1.7.10.jar) 
UCHIJA OpenComputers{1.6.0.9} [OpenComputers] (OpenComputers-MC1.7.10-1.6.0.9-universal.jar) 
UCHIJA OpenAutomation{1.7.x-b218} [OpenAutomation] (OpenAutomation-1.7.x-b218.jar) 
UCHIJA OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
UCHIJA OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
UCHIJA progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.35.jar) 
UCHIJA quantumflux{1.7.10-1.3.4} [QuantumFlux] (QuantumFlux-1.7.10-1.3.4.jar) 
UCHIJA RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
UCHIJA RefinedRelocation{1.1.28} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.28.jar) 
UCHIJA ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
UCHIJA rftools{4.23} [RFTools] (rftools-4.23.jar) 
UCHIJA RouterReborn{1.2.0.43} [Router Reborn] (RouterReborn-1.7.10-1.2.0.43-universal.jar) 
UCHIJA SGCraft{1.11.3} [Greg's SG Craft] (SGCraft-1.11.3-mc1.7.10.jar) 
UCHIJA SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
UCHIJA superMassiveTech{MC1.7.10-0.4.0-alpha-114} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.4.0-beta-114.jar) 
UCHIJA TardisMod{0.995} [Tardis Mod] (tardismod-1.7.10-0.995-350.jar) 
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
CoFHCore: -[1.7.10]3.1.3-327
Mantle Environment: Environment healthy.
List of loaded APIs: 
* appliedenergistics2|API (rv2) from tardismod-1.7.10-0.995-350.jar
* armourersWorkshopAPI (1.7.10-10.13.4.1448-1.7.10) from Armourers-Workshop-1.7.10-0.42.4.jar
* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
* CoFHAPI (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.39_beta.jar
* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
* CoFHAPI|core (1.7.10R1.1.0) from NuclearCraft-1.9d--1.7.10.jar
* CoFHAPI|energy (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHAPI|inventory (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.43-universal.jar
* CoFHAPI|item (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar
* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHAPI|tileentity (1.7.10R1.1.0) from NuclearCraft-1.9d--1.7.10.jar
* CoFHAPI|transport (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
* CoFHAPI|world (1.7.10R1.1.0) from NuclearCraft-1.9d--1.7.10.jar
* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
* ComputerCraft|API (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|FileSystem (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|Lua (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|Media (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|Peripheral (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|Permissions (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|Redstone (1.75) from tardismod-1.7.10-0.995-350.jar
* ComputerCraft|API|Turtle (1.75) from tardismod-1.7.10-0.995-350.jar
* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.463.jar
* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
* MekanismAPI|core (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|energy (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|gas (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|infuse (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|laser (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|reactor (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|recipe (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|transmitter (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* MekanismAPI|util (9.0.0) from NuclearCraft-1.9d--1.7.10.jar
* minechemAPI (1.7.10R1) from Minechem-1.7.10-5.0.5.406.jar
* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.5.1.jar
* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
* RefinedRelocationAPI (1.0.0) from RefinedRelocation-mc1.7.10-1.1.28.jar
* Thaumcraft|API (4.2.2.0) from tardismod-1.7.10-0.995-350.jar
* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
EnderIO: Found the following problem(s) with your installation:
* The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.429_beta.jar).
It is a supported version, but that difference may lead to problems.
This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Modpack Version: 1.6.4
Stencil buffer state: Function set: GL30, pool: forge, bits: 8
Launched Version: forge-10.13.4.1614
LWJGL: 2.9.1
OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by Sir-Will** [comment]
Remove the entities with mcedit.
