### ISSUE TITLE
Game crashes when pressing R on items in the quest book

### ISSUE THREAD

**Issue by SWJ0k3r** [MyM-ModpackTeam/GalacticScience#183]
Open the quest book, go to a quest that requires an item, hover on the required item with the mouse and press the R key. This used to take you to the recipe in JEI, now it just crashes the game. This started happening after the most recent update.

Attached is my crash log.
[crash-2019-08-24_10.03.12-client.txt](https://github.com/MyM-ModpackTeam/GalacticScience/files/3537413/crash-2019-08-24_10.03.12-client.txt)

**Comment by Sir-Will** [comment]
I'm unable to reproduce this issue.
