### ISSUE TITLE
4Space update failed

### ISSUE THREAD

**Issue by epiclucas2050** [MyM-ModpackTeam/GalacticScience#184]
Hello ,i have a problem with the server file of galactic science...
When i start the server by CMD,i get an error who say me "[19:38:26] [Thread-10/ERROR] [4Space]: 4Space update check failed! Trying again in 15 seconds" but it never work
I re-start the cmd , i download an other time the server.zip but it will ever stay on this error message
Thx for the help
I send to you the cmd screen
![Capture d’écran (25)](https://user-images.githubusercontent.com/56316269/66419079-b1c83400-ea03-11e9-893c-79ba605dfdfb.png)

**Comment by L-o-r-d-V-i-l-e** [comment]
I've had the same issue. But when I reloaded the server the message did not appear and I could connect to the Server

**Comment by L-o-r-d-V-i-l-e** [comment]
Have you tried to ignore the "error message" and just connect to the server?

**Comment by TheProoNooob** [comment]
> Have you tried to ignore the "error message" and just connect to the server?

doesn't work. the world hasn't generated to join the server.

**Comment by rktfier** [comment]
> 
> 
> > Have you tried to ignore the "error message" and just connect to the server?
> 
> doesn't work. the world hasn't generated to join the server.

Tested server on Arch Linux with openjdk8, error message appears but players are able to join server.

**Comment by Sir-Will** [comment]
Set `B:"Enable Update Checking?"=true` to false in config/4Space/core.cfg
