### ISSUE TITLE
Mod issue

### ISSUE THREAD

**Issue by GrimReaperRo** [MyM-ModpackTeam/GalacticScience#185]
the machine (wood chooper wood farmer wooden killer and other) have rn a bug wich crash the use when they try to acces the interface of them

**Comment by rktfier** [comment]
> 
> 
> the machine (wood chooper wood farmer wooden killer and other) have rn a bug wich crash the use when they try to acces the interface of them

Any steps to replicate? Have been using them for long time and had no problems.
