### ISSUE TITLE
GalacticScience won't download

### ISSUE THREAD

**Issue by AsO43** [MyM-ModpackTeam/GalacticScience#186]
When I try to download this modpack in twitch on a mac, this message pops up:
"Unable to get Addon: Galactic Science (232015) - File ID: 2761972"

Could someone help me with this issue or tell me another way to play this pack?

**Comment by Sir-Will** [comment]
I'm unable to reproduce this issue. Please try whitelisting the twitch launcher from your anti virus program.

Otherwise you will have to contact the CurseForge support here: https://twitchpartnerships.force.com/curseforge/s/contactsupport
