### ISSUE TITLE
Trying to set game up for 6 users.

### ISSUE THREAD

**Issue by L33Tech** [MyM-ModpackTeam/GalacticScience#188]
ONE INSTANCE WORKED. All the others randomly died and crashed after MULTIPLE CLEAN REINSTALLS.

**Comment by Excellent12** [comment]
ahjhhkhhjkfdhkfrh;jl it no work

**Comment by Sir-Will** [comment]
Please upload the log and crash report.

**Comment by L33Tech** [comment]
@Excellent12 Can you send your report here? Mine worked.

**Comment by Aiidoneus** [comment]
Seems like you solved your own issue.
