### ISSUE TITLE
Triple/Quadruple compressed cobble not able to be decomposed (Information needed)

### ISSUE THREAD

**Issue by NolanSyKinsley** [MyM-ModpackTeam/GalacticScience#19]
It is a known bug with minechem that something causes triple and quadruple compressed cobblestone to be un-decomposable at various times for unknown reasons. I don't know a fix to the root cause, but I know I can hard code the recipes into minechem using minetweaker. The only issue is that I do not know what ratios to use.

In cobblestone there are 4 or 5 outputs possible with a 10% chance per cobble, and once you get into double and triple compressed cobble the recipes seem to go haywire, with multiple identical outputs and doubled outputs etc.

I can fix all this using the base cobble output as a reference, but only if I make it 1/9 output instead of 1/10 per cobble. This will lead to a possible increase in output from current standards for quadruple compressed, but as we cannot currently decompose quad compressed cobble IDK how exactly we would compare it. 

I have a feeling that all though mathematically it seems to show a buff, from what I saw in the recipes there were many duplicates and loops that may have been leading to extra output. I think issuing a specific recipe for double/triple/quad compressed cobble may actually lead to a slight nerf.

If I get permission from you I will go ahead with implementing standardized decomposer minetweaker recipes for compressed cobble up to quad using the 1/9th output per cobble instead of the current 1/10th output per and submit a pull request with my finalized recipe list.

**Comment by Slind14** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/issues/4

**Comment by Slind14** [comment]
@drz2k thats up to you I guess.

**Comment by drz2k** [comment]
If you want, go ahead, thoo with obsidian, not many do the cobble decomp anymore ;)

**Comment by drz2k** [comment]
Ill publish 1.4.9 this weekend. Do we get a pull request?
