### ISSUE TITLE
 Project is abandoned at CurseForge

### ISSUE THREAD

**Issue by rktfier** [MyM-ModpackTeam/GalacticScience#192]
Is this intentional?

**Comment by Sir-Will** [comment]
It's not, thank you for letting us know. We will look into it.

**Comment by Seniorendi** [comment]
Well, it's still abandoned 
![image](https://user-images.githubusercontent.com/67484093/107037657-ac2b5b80-67bb-11eb-8054-a532dddbdb43.png)

**Comment by Sir-Will** [comment]
I'm aware and there is nothing we can do unfortunately. They refuse to transfer the project from the previous maintainer.

**Comment by Seniorendi** [comment]
Is it bad that the Projekt is abandoned? I mean I can install it and everything works.

**Comment by Sir-Will** [comment]
Well, it gives the wrong information and some people will not try to see if it works or not.

**Comment by Timtower** [comment]
@Sir-Will 
![nlzwUvk](https://user-images.githubusercontent.com/3043612/111590448-67391280-87c6-11eb-82e0-e844cec89cfb.png)

**Comment by Sir-Will** [comment]
@Timtower on which Discord is that, and what's the role of Gilgamesh?
I already opened a support ticket multiple months ago, but they refused to do anything.

**Comment by Timtower** [comment]
@Sir-Will Curseforge, one of the staff channels.
Gilgamesh is one of the Curseforge leads now.
Feel free to directly ping me on the curseforge discord if you have any questions.

**Comment by Sir-Will** [comment]
Should be good now.
