### ISSUE TITLE
Modpack crashes at launch w/ CurseForge

### ISSUE THREAD

**Issue by KTShadow3432** [MyM-ModpackTeam/GalacticScience#194]
Ever since Twitch's modpack launcher moved to Overwolf/CurseForge, the modpack itself cannot even launch, crashing immediately after it loads in the Minecraft Launcher that pops up after hitting Play. Exact Error message reads: "An expected issue occurred and the game has crashed. we're sorry for the inconvenience. Exit Code: 0"

I believe this is a problem with the modpack specifically and not CurseForge, seeing that other modpacks such as R.A.D. and RLCraft launch and run just fine with no crash errors..

**Comment by KTShadow3432** [comment]
Update: This issue is with the current version of the mod- 1.6.9, previous version 1.6.4 runs just fine.

**Comment by Sir-Will** [comment]
Thanks for the report, I just pushed an update which fixes it, and it should be on CurseForge once it is approved.
If you don't want to wait you can download the curse profile and import it:
https://github.com/MyM-ModpackTeam/GalacticScience/releases/tag/1.6.10
