### ISSUE TITLE
[Suggestion] AE2 for Galactic Science

### ISSUE THREAD

**Issue by HaRo0** [MyM-ModpackTeam/GalacticScience#196]
Hey there,

I have been playing this pack for a long while now and the only thing I always wanted to be added to it was Applied Energistics, so I wanted to ask if it would be possible to add it to the pack.
It doesn't have to be available in early game, mid/late game would be more than enough.
All that would have to be added is certus quartz, charged certus quartz, Sky Stone and the plates.

That could be achieved by sieving asteroid stone for sky stone dust, which would be put in a stone barrel with water to get Sky Stone.

For Certus and Charged Certus there would be 2 options, either it is available by sieving asteroid stone aswell.
Or by using the Blood Altar Tier 7, in which case Certus Quartz would be obtainable by putting Naquadah ingots inside the Altar. and Charged Certus would be obtainable by putting a Stargate Core Crystal inside, as you only need 1 Charged Certus Quartz to craft a charger.

The plates could be available by trading them in the Questbook.

This are just ideas I have had, there are many other ways to make them available, if the mod would be added.

-HaRo0

**Comment by Sir-Will** [comment]
It is intentional that this mod is not in the modpack, adding it would negatively impact the goal of being something fresh without popular and  common mods.

Also, the 1.7.10 version of the modpack will not receive any mod changing updates.
