### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by TemporalAnomaly** [MyM-ModpackTeam/GalacticScience#2]
I generated a new world, punched down a tree, was breaking the dirt under the tree, and i crashed before it finished breaking. Here is the log: http://pastebin.com/jvtzbVK1
I hope this helps

**Comment by Slind14** [comment]
Looks like galactic craft can't write to a specific directory:
```
[14:19:54] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.network.PacketSimple:handleClientSide:781]: Cannot create directory %minecraftDir%/assets/temp!
```
Did it create a crash report with more information, maybe?

**Comment by TemporalAnomaly** [comment]
None besides the standard logs, unfortunately.

**Comment by Slind14** [comment]
I'm not entirely sure if this is the reason of the crash, but could you try to delete the tmp directory?
`C:\Users\Brooks\AppData\Roaming\.mineyourmind\instances\MyM-GalacticScience\minecraft\`

**Comment by SirWilli** [comment]
I will close this for now. If it happens again feel free to reopen it.
