### ISSUE TITLE
Earth (overworld) no longer exists.

### ISSUE THREAD

**Issue by MrKovacic** [MyM-ModpackTeam/GalacticScience#201]
In v 1.6.10, when traveling to the earth, I end up somewhere with a starry background, no ground, and I am in a constant state of using the parachute. The ground seems moon colored and there is one single star tile square on the floor, however I can not touch the floor, I am hovering. I cant move anywhere or do anything. The only way to get back to the moon is to restart the game.

**Comment by Sir-Will** [comment]
The overworld is disabled, you are not supposed to go there.
