### ISSUE TITLE
Satellite infinite death bug

### ISSUE THREAD

**Issue by TheDawgMiner** [MyM-ModpackTeam/GalacticScience#28]
Falling/Jumping off the Satellite with parachute causes player to spawn in a void world causing player's death & re-spawning in same void world. 

Possible Cause: Overworld disabled?

Possible fix: Enable Overworld and add COFH Core and set .cfg to no ore spawn?

**Comment by SirWilli** [comment]
What speaks against disabling the parachute?

**Comment by drz2k** [comment]
Nothing against it. Fix until then - open to lan with cheats /cofh tpx -28

**Comment by NolanSyKinsley** [comment]
I could have sworn there was a config option to disable this feature, but after perusing the source and asking in IRC it seems there is no such feature as it is hard coded [here](https://github.com/micdoodle8/Galacticraft/blob/47d1df6bb531654179201e7caa16a4a1586839ac/src/main/java/micdoodle8/mods/galacticraft/core/dimension/WorldProviderOrbit.java#L529) So it would require customizing the source to change, but if you are going to edit the source then you may as well just change it to orbit mars a few lines up.

**Comment by SirWilli** [comment]
@NolanSyKinsley I mean remove the recipe

**Comment by NolanSyKinsley** [comment]
Oh, that won't help... the parachute is for in case you have to bail from a space ship, it is not a prerequisite for being teleported to the overworld dimension when falling from the satelite, it is just supposed to keep you from dying when you do, but seeing as how there is no overworld it hasn't a chance of doing that due to void damage.

**Comment by Slind14** [comment]
@SirWilli onEntitySpawn if player and world is dim 0, tp to -28 spawn location?
