### ISSUE TITLE
save world

### ISSUE THREAD

**Issue by trint10** [MyM-ModpackTeam/GalacticScience#29]
i am doing a YouTube let-play and, out of know where my old will not load up and saying it a bug and something could be miss up with the / progress
what can i do. help for i can get back to playing and don't have to start all over ether  

forge mod loader detected that the backup level.dat is being used

This may happen due to a bug or corruption, continuing can damage your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

**Comment by Slind14** [comment]
Can you be more precise and cover more about your issue? I don't understand enough in order to be able to help.

**Comment by trint10** [comment]
let me take a screen shot will that help more

**Comment by trint10** [comment]
forge mod loader detected that the backup level.dat is being used

This may happen due to a bug or corruption, continuing can damage your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

**Comment by Slind14** [comment]
Copy the saves  another location (backup) and proceed. If it corrupts you world you still have the backup.

**Comment by trint10** [comment]
i did that and it wont let me go anywhere else

**Comment by Slind14** [comment]
What happened before this occurred?

**Comment by trint10** [comment]
idk, i was playing it this morning run just fine, got off game thin at night go to do another recording and it showing up now.

**Comment by Slind14** [comment]
The issue here is that the leve.dat contains the item ids. Meaning we can't just use another or new one. Do you mind zipping and uploading the world if it isn't too big?

**Comment by trint10** [comment]
there you go

**Comment by trint10** [comment]
where do i send it at, i just zip it

**Comment by Slind14** [comment]
drop box or whatever you use.

**Comment by trint10** [comment]
need email to share with you throw dropbox

**Comment by Slind14** [comment]
`Share link`

**Comment by trint10** [comment]
https://www.dropbox.com/sh/z286m2qsvz7odmm/AAD1UC2VenJWfXs3jiwChGAqa?dl=0

**Comment by Slind14** [comment]
thank you. Which version of the pack and launcher are you using?

**Comment by Slind14** [comment]
it seems to be missing files. It only contains 4 regions of the overworld, the world where you never go to in the pack.

**Comment by trint10** [comment]
https://www.dropbox.com/s/m9nqn4bhla81ah1/world.zip?dl=0
the newest one

**Comment by Slind14** [comment]
This is how a **new** galactic science world looks like. All those DIM-nn's are missing in yours, are you sure that you looked at the right location?

**Comment by trint10** [comment]
that was my back up one, i can show you the main one

**Comment by trint10** [comment]
going to send you the hole folder be a few sec for it to be put on dropbox

**Comment by Slind14** [comment]
if that is your backup, you can delete it, because it doesn't contain the world. The moon is DIM-28

**Comment by trint10** [comment]
https://www.dropbox.com/s/j64d8ld6r8zpd2p/saves.zip?dl=0

**Comment by Slind14** [comment]
I'm sorry, I could not figure out what is wrong with it. I can only tell that it is totally mixed up. Like two saves being copied into each other.
The zip contains two saves, both named the same, but only one will show up ingame. The one that does, does not have a DIM-28. The other that does not show up, also doesn't show up if you load it alone (delete the other). Copying the level.dat from the other world over does let it show up but loading causes the same bug. How much time did you spend on it yet?

**Comment by trint10** [comment]
i did 1 video on it only, and i think i got throw one night time only and just trun day time when i was going to do recording-https://www.youtube.com/watch?v=BEGAeqIYnLs

**Comment by drz2k** [comment]
Probably best to start a new world. Then go ESC-open to lan-enable cheats.

Use /hqm edit and unlock the quests you had. Then /gamemode 1 - cheat in what you miss - /gamemode 0.

Save, enter, play more :)

**Comment by trint10** [comment]
ok thanks, just wanted to report the bug  and help out.
