### ISSUE TITLE
Random Nether Portals when I completely close the game and reopen

### ISSUE THREAD

**Issue by vekenti** [MyM-ModpackTeam/GalacticScience#30]
When I close the minecraft game completely,reopen it, and launch my world, theres a random nether portal near or in my base, it gets really annoying because i have to go into creative to destroy them, any ideas what is causing this?

**Comment by SirWilli** [comment]
Same with a new world and both templates?

**Comment by vekenti** [comment]
I didnt try the observatory template, but the default one had the problem even when i deleted my game folder and reinstalled the modpack completely

**Comment by NolanSyKinsley** [comment]
What version of java are you using?

**Comment by drz2k** [comment]
Id really like to see this in a reproducable way since theres just really no mechanic i can think of that does this stuff.

**Comment by Slind14** [comment]
@vekenti maybe try building on near by where you don't care. 
Overall we will need to find a way of reproducing it to get any further.

**Comment by SirWilli** [comment]
The nether portal seems to only spawn when you load the world with a different account.
