### ISSUE TITLE
NEI mob overlay (F7) not working

### ISSUE THREAD

**Issue by Ronzan** [MyM-ModpackTeam/GalacticScience#31]
Something seems to be conflicting with the NEI mob/lighting overlay (F7) function.
Nothing happens when you press F7.

Update:
It works on Mars, but not on the moon. I will update as I reach other planets.

Pack version: 1.4.12
Launcher: Curse
Additional mods: None

**Comment by drz2k** [comment]
Just rebind the streaming F7 in controls.

**Comment by Ronzan** [comment]
Just read my initial post!

Kidding aside, I have nothing else bound to F7.

**Comment by drz2k** [comment]
well it seems hardcoded in some way. changed the button to several other ones, none wont bring up the spawn indication. probably an issue with nei itself.

**Comment by SirWilli** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/commit/b64de34eee0ad6044d18ed45161735560c80e5d4 seems to fix the issue
