### ISSUE TITLE
Item texture issues

### ISSUE THREAD

**Issue by QCU87Z** [MyM-ModpackTeam/GalacticScience#32]
There is an issue with item icons in the quest book and inventory, using recommended pack off FTB launcher. Fresh install.

Wood icons + super massive tech icons noticed so far

![2015-10-16_11 09 55](https://cloud.githubusercontent.com/assets/7598686/10531539/7cf24ffe-73f6-11e5-8700-b49daeab0c25.png)

**Comment by NolanSyKinsley** [comment]
If you haven't gotten too far into the game, verify your game cache and start again, or just wipe the folder and try a fresh download. I haven't seen this reported by anyone else as of yet so I believe this to be a one-off bug.

**Comment by QCU87Z** [comment]
Same thing again tried on a different computer I cleared out the whole FTB folder

**Comment by Slind14** [comment]
GPU driver up to date?

**Comment by QCU87Z** [comment]
Yes on mac all up to date only pack that gives me this issue no resource packs loaded on top of the MC original.

**Comment by QCU87Z** [comment]
If i run the pack with MultiMC all the graphics work?! I will just use multimc

**Comment by drz2k** [comment]
Is that question or a feedback ? ;)

**Comment by QCU87Z** [comment]
feedback sorry, It works with Multimc

**Comment by drz2k** [comment]
So this should be a download/pc issue. Closing :)

**Comment by dawgermany** [comment]
same on my mac
