### ISSUE TITLE
Incomplete Quest - Chapter 5

### ISSUE THREAD

**Issue by SirWilli** [MyM-ModpackTeam/GalacticScience#35]
![](https://i.imgur.com/K7XBJLK.png)

**Comment by Geekerandy** [comment]
isn't this stuff done?

**Comment by jaspercayne** [comment]
![2015-11-28_03 12 51](https://cloud.githubusercontent.com/assets/6414853/11450872/06f1effe-957e-11e5-8de5-2aa645e144eb.png)

Quest was completed as soon as I unlocked it, but provides no rewards, does not appear to have any task type association to it (detection, crafting, etc), and has no text at all in the page.
