### ISSUE TITLE
Unable to craft Fuel Pellets, Recipe Conflict

### ISSUE THREAD

**Issue by yosomith** [MyM-ModpackTeam/GalacticScience#38]
There is currently a recipe conflict with Fuel Pellets which is crafted in a shapeless recipe of 1 coal or charcoal to 8 pellets. Currently trying to craft them only nets you Fragmented Carbon.

**Comment by drz2k** [comment]
I tried to fix this multiple times in the past and the mods involved arent fixing it as well. Since we have better alternatives on GS i stopped caring ;)
