### ISSUE TITLE
One of four worlds lost in singleplayer, yet still appears in the configs.

### ISSUE THREAD

**Issue by Geekerandy** [MyM-ModpackTeam/GalacticScience#39]
I've never seen this before. I didn't do anything different, just went on, played, the next day, the world I was playing is gone. Anyone experience this before? When I check my saves, I see the world still there, so it's just not loading.

Here's a Log, just in case you need it.
http://paste.feed-the-beast.com/view/3253fa95

**Comment by SirWilli** [comment]
Looks like an issue with the level.dat

Can you try to rename ore move both level.dat files out of your singleplayer world folder and see what happens?

````
[20:13:20] [Client thread/ERROR]: Exception reading C:\Users\Ve Nguyen\Documents\Material energy\GalacticScience\minecraft\saves\Third World, 1st of Observatory\level.dat
java.util.zip.ZipException: Not in GZIP format
```

**Comment by Geekerandy** [comment]
All right, modpack loading up now. You guys work hard to respond quickly. Is it like notified on your phone?
I moved the level.dat files (the old and new one) out into the saves folder. Let's see what happens.

**Comment by SirWilli** [comment]
I get an email and a notification on our community chat

**Comment by Geekerandy** [comment]
I see. So I could spam a billion times to fill up your E-Mail XD (then you guys would mute me or something) ( ͡° ͜ʖ ͡°)

**Comment by Geekerandy** [comment]
Back, and the world is still missing. Here's the log (Note: still contains the log from original post)
http://paste.feed-the-beast.com/view/f7ebf086

**Comment by SirWilli** [comment]
Okay, can you undo your level.dat change and upload the world? I will look later if I can fix the world.

**Comment by Geekerandy** [comment]
How do I upload the world?

**Comment by SirWilli** [comment]
Zip it and upload it to dropbox, mediafire or something like this

**Comment by SirWilli** [comment]
You maybe can also upload it here if you drag and drop it into the text box

**Comment by Geekerandy** [comment]
Ah, when I compress it it turns it into a WinRaR zip, and thats not accepted!

**Comment by Geekerandy** [comment]
Ima just download to dropbox, here and now.

**Comment by Geekerandy** [comment]
Sorry @SirWilli, but I have to go to sleep for the night. Great modpack, (and changed configs, XD) and I will get back to you in...18 hours?

**Comment by SirWilli** [comment]
Alright

**Comment by Geekerandy** [comment]
before I go to bed. I finally got it:
https://www.dropbox.com/sh/y8lsl3z572p5bmf/AADqKcxlEO6qA9dN9bZjJTipa?dl=0

**Comment by SirWilli** [comment]
Ok, got an fix for you. Go into the maps/Observatory folder in your modpack directory and copy the level.dat then paste it in your world folder.

**Comment by Geekerandy** [comment]
Hello, just a quick update before I get to school, the singleplayer world appears, but when I try to load up the world, it crashes and I am back to the launcher. Also with that level.dat file, I had replaced the other level.dat file. 
Here's the log:
http://paste.feed-the-beast.com/view/755ce9fd

**Comment by SirWilli** [comment]
Your questing data seems to be corrupted too. You have to delete the players.dat in the HardcoreQuesting folder. You can try if the backup works.

**Comment by Geekerandy** [comment]
Man, I wonder what caused all this. Welp, time to fix files, go eat, bathroom, all that jazzy jazz.

**Comment by Geekerandy** [comment]
Man, all you guys are awesome. Diligently working on a modpack that I am addicted to (in fact, more addicted than the material energy series, and thats ALOT) I wish I could donate but sadly I am not of age of which I can do such a thing.

**Comment by Geekerandy** [comment]
All right, world loaded up, but now I am in the void.

**Comment by Geekerandy** [comment]
I heard there was a command to get back to the moon in the exact spot needed.

**Comment by Geekerandy** [comment]
Found it. On this:
http://forum.feed-the-beast.com/threads/1-7-10-hqm-survival-galactic-science-something-fresh.86203/page-41

/cofh tpx -28.

**Comment by Geekerandy** [comment]
Welp, I come back the moon using that command, and I spawn next to a space lander. Looks like everything is intact, my base is nowhere in sight.

**Comment by Geekerandy** [comment]
I used the coordinates of a different world I had, open to LAN and to the coords, and everything looks normal. So the solution to the problem is to delete the player.dat file in the HardcoreQuesting file. Welp, time to close this now. Thank you for everything! P.S, I lost all my player progress because I deleted the player.dat file. Oh well, /hqm edit mode!

**Comment by Geekerandy** [comment]
ONE LAST NOTE! All um *cough* XU generators *cough* Changed configs *cough* turned into TNT from the Dalek Mod. Must be a consequence or something.

**Comment by SirWilli** [comment]
@Geekerandy the level.dat contains the information on which item ID does have which item name. As your old level.dat had different data it turned them into tnt but as long as there are not too many blocks you should be fine replacing them in creative mode.

**Comment by Geekerandy** [comment]
Ah, I see. Thank you for that. Welp, I can replace everything with creative
