### ISSUE TITLE
Compressed cobblestone Double and above not recognized by decomposer

### ISSUE THREAD

**Issue by DavidMetcalfe** [MyM-ModpackTeam/GalacticScience#4]
The Chemical Decomposer used to take compressed cobblestone at Double and higher densities, and since the last update, does not appear to recognize them. Now, it will only take the base level of compressed cobblestone.

![2015-08-04_10 46 54](https://cloud.githubusercontent.com/assets/80915/9068085/2c1b138e-3a96-11e5-8189-1b4dc96e42ce.png)

**Comment by SirWilli** [comment]
Tempfix: place the compressed cobblestone in the decomposer and restart your game.
See: https://github.com/jakimfett/Minechem/issues/791#issuecomment-128198136
