### ISSUE TITLE
(Minor Bug) Carpenter's Blocks from Carpenter's Blocks Mod is not quieted down on the moon.

### ISSUE THREAD

**Issue by Geekerandy** [MyM-ModpackTeam/GalacticScience#40]
So on the moon unless you have a frequency module, everything sounds very quiet, or not heard at all. But the Carpenter's Blocks are normal, and scared me with the "thumping" from mining it.
This isn't too big of a thing, and I think just putting a label of "minor" and possibly "bug" is fine. Or is it "mod issue" and not a bug?

**Comment by drz2k** [comment]
Well its the mod bypassing that sound rule. You probably could try to alert GC or carpenters dev to fix this. Nothing that i could do here.

**Comment by Geekerandy** [comment]
Okay. That's it then, thank you!
