### ISSUE TITLE
Place down one tube of Minechem Chemical, get 8 empty tubes back, and a entire chemical source block spawns.

### ISSUE THREAD

**Issue by Geekerandy** [MyM-ModpackTeam/GalacticScience#42]
My friend said this was a glitch he found out randomly, so you right-click the ground with only ONE of the chemical tube (he did sucrose and it requires eight tubes of any chemical), and he gets eight empty tubes back, and a full source block of the liquid sucrose. But when he tries to pick it back up with the eight tubes, it turns back into one tube. But, he can also transfer it around in a bucket.

**Comment by Geekerandy** [comment]
Update: I can't replicate it. Must be his computer.

**Comment by drz2k** [comment]
It can happen due to lag. Is a mod issue that has been reported quite some time before. Lets just hope he fixes it :)

**Comment by Geekerandy** [comment]
Thank you!
