### ISSUE TITLE
MyM Server: Crash when right clicking stone chopper

### ISSUE THREAD

**Issue by Geekerandy** [MyM-ModpackTeam/GalacticScience#43]
Welp, right click = crash.
On the MyM Server.
Does not crash in singleplayer.
Crash Log:
http://paste.feed-the-beast.com/view/2abc98b1

**Comment by SirWilli** [comment]
Same issue with a new Stone Chopper? It could be that the item in the chopper is the issue

**Comment by Geekerandy** [comment]
I will test it soon.

**Comment by Geekerandy** [comment]
All right, replaced it, still crashed.

Crash Log: http://paste.feed-the-beast.com/view/69a94416

**Comment by SirWilli** [comment]
What do you place into the stone chopper and did you already reinstall the pack?

**Comment by Geekerandy** [comment]
I didn't reinstall the pack yet, and it was just stone upgrades, charcoal, and a stone axe. I didn't reinstall the pack yet.
I even mined it up, placed it down again, right clicked, crash.

**Comment by Geekerandy** [comment]
Force Updated it, now works and doesn't crash. Thank you!
