### ISSUE TITLE
World corrupted?!

### ISSUE THREAD

**Issue by Mister-Mine** [MyM-ModpackTeam/GalacticScience#45]
i wanted to play this modpack, but than this stand:

Forge Mod Loader detected that the backup level.dat is being used.
This may happen due to a bug or corruption, continuing can damage your world beyond repair or lose data/progress.
it's recommended to create a world backup before continuing.

what can i do? because when i copy this world the same thing stand there and when i use "Re-Create" than i lose my progress.

**Comment by SirWilli** [comment]
Do you have an backup of the world?

**Comment by Mister-Mine** [comment]
not before this bug

**Comment by Mister-Mine** [comment]
It works again, Thank you.

**Comment by FlarpMaster** [comment]
I've deleted the two level.dat files from the maps folder, then replaced it with the level.dat file from my world save file. But that didn't do anything
