### ISSUE TITLE
1.5 Major Mod Updates

### ISSUE THREAD

**Issue by Slind14** [MyM-ModpackTeam/GalacticScience#46]
## Updates available
- [x] ChickenCore (47)
- [x] Ex-Astris (Rebirth 1.15)
- [x] Ex-Nihilo (1.38-48)
- [x] ModTweaker (0.9.4)
- [x] NotEnoughItems (1.0.5.118)
- [x] NeiAddons (1.12.14.40)
- [x] Galacticraft Planets (3.0.12.404)
- [x] MicdoodleCore (3.0.12.399)
- [x] Tradis (0.99-207)
- [x] Darkcore (0.3-45)
- [x] DalekMod (U39)
- [x] MineTweaker (3.0.10B)
- [x] SuperMassiveTech (0.4.0-alpha-113)
- [x] Advanced Generators (0.9.18.116)
- [x] BloodMagic (1.3.3-17)
- [x] Carpenter's Blocks (3.3.7)
- [x] Chisel 2 (2.5.1)
- [x] Custom Main Menu (1.9.2) @SirWilli quite some changes, better you do it, to make sure it is smooth
- [ ] ~~Ender IO (only beta releases available)~~
- [ ] ~~Endercore (only beta releases available)~~
- [x] Ex Nihilo (1.38.49)
- [x] Extra Utilities (1.2.12)
- [x] HQM (4.4.1 remove notimefix)
-  ~~Modular Systems (2.2.1, major update, **blocks being wiped from map**)~~
- [x] OpenBlocks (1.4.4)
- [x] OpenComputers (1.5.19.37)
- [x] QuantumFlux (1.3.2-b4)
- [x] Refined Relocation (1.1.12)
- [x] RFTools (4.0.1, **major update 2.x -> 4.x**)
- [x] Router Reborn (1.2.0.35)
- [x] Solar Flux (0.8b)
- [x] Inventory Tweaks (1.59-dev-152)
- [x] Armourers-Workshop (0.37.0.94)

**Comment by SirWilli** [comment]
I talked with @drz2k about it and he said to better not update it as the new version will wipe everything and does have many bugs.
