### ISSUE TITLE
/help Crash

### ISSUE THREAD

**Issue by Kalbintion** [MyM-ModpackTeam/GalacticScience#47]
Running a local server on 1.4.14 from the FTB launcher that I connect via running the pack from the launcher itself. Using the command /help 15 causes the client to crash out with an error message. Attempting to do this with an Open to LAN option causes game to crash.

```
Connection Lost

Internal Exception: io.netty.handler.odec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"clickEvent":{"action":"suggest_command","value":"/INpureCore "}} into a Component
```

Not sure what mod that command is from (/INpureCore from the value of the error message) as using it does nothing in response to client or console.

**Comment by SirWilli** [comment]
Mod author is inactive so I don't think there will come any fix from him.
