### ISSUE TITLE
[Questbook] Jars at the ready issue

### ISSUE THREAD

**Issue by micmou** [MyM-ModpackTeam/GalacticScience#48]
In version 1.4.14 I did the barrel quest and crafted a barrel but for whatever reason it refuses to recognize that I did so.

I use the Ex Astris Rebirth Oak barrel recipe with 6 planks and a half slab and crafted it using a normal workbench to no avail proof below.

http://i.imgur.com/gvbYBFp.png

**Comment by SirWilli** [comment]
Thanks for the report, will be fixed with the next update. Use /hqm edit to complete the quest for now and let us know if you find another bug.

**Comment by micmou** [comment]
I have a secondary question is there any server files anywhere. You have mention of them in your posts but I have been unable to find them anywhere? I would like to host it on our dedi for some firends.

**Comment by Slind14** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/releases

**Comment by micmou** [comment]
@Slind14 Thank you very much you should think about putting the server file on the ftb launcher in the download server files part I totally spaced even checking github...

**Comment by Slind14** [comment]
It should be on there for the recommended version.

**Comment by micmou** [comment]
Ohh I was using the next version up wow I need to stop doing things at 3 in the morning...

**Comment by Slind14** [comment]
no problem. We even appreciate you using the next version, but be aware that it includes major mod updates and hence quite a few things are broken and needing reporting.
