### ISSUE TITLE
Gas turbine from advanced generators eat fuel and not generating RF

### ISSUE THREAD

**Issue by Cornosx** [MyM-ModpackTeam/GalacticScience#5]
I create fuel from galactic craft and transport it to gas turbine. Gas turbine eat 5000 MB of fuel and not generating RF.

**Comment by SirWilli** [comment]
I think it doesn't support galacticraft fuel atm. At least the wiki doesn't list it:
http://bdew.net/generators/turbine-generator/

**Comment by drz2k** [comment]
SirWilli is correct. You need the rocket fuel from EIO for the generators. Its a bit misleading that both name it the same way.
