### ISSUE TITLE
Can't join the Server? Same with a friend.

### ISSUE THREAD

**Issue by Hiddenisme** [MyM-ModpackTeam/GalacticScience#52]
This was taken few minutes ago and we still can't join...
![image](https://cloud.githubusercontent.com/assets/1483674/11315054/b8e46926-8fb1-11e5-9675-eaa1f06b31c4.png)

As of Thursday 11/19/2015, Upon attemping to join the server we get this...
![image](https://cloud.githubusercontent.com/assets/1483674/11315047/a53c9204-8fb1-11e5-9fe7-bd8b22178efa.png)

**Comment by Bennyboy1695** [comment]
use galactic.mym.li instead of the numbered ip
