### ISSUE TITLE
Strange errors that break how the game is played.

### ISSUE THREAD

**Issue by stevenmlittle** [MyM-ModpackTeam/GalacticScience#53]
I think some of the mods randomly broke and even after re-downloading the pack it still is broken I have the console logs if that makes any difference. I really enjoy this pack and would like to continue playing but these problems just make playing fell odd.
[errors.pdf](https://github.com/MyM-ModpackTeam/GalacticScience/files/43269/errors.pdf)

**Comment by SirWilli** [comment]
That's no full log, please post the full log via www.pastebin.com or gist and which version are you using?

**Comment by stevenmlittle** [comment]
http://pastebin.com/vKY326kT is everything that FTB spits out to me in the process of opening FTB and launching the pack. Side note there is a lot of useless things in the log have fun, and thank you.

**Comment by SirWilli** [comment]
What exactly is the issue? What doesn't work?

**Comment by stevenmlittle** [comment]
It seems to have fixed itself but thanks for the concern.
