### ISSUE TITLE
EnderIO Crafter Pointless

### ISSUE THREAD

**Issue by Kalbintion** [MyM-ModpackTeam/GalacticScience#56]
The EnderIO Crafter takes 2500 RF / craft compared to the RFTools Crafter 1000 RF / craft - Considering the EnderIO Crafter takes desh to craft due to the frame, and only does one recipe per machine, on top of being slower (even with an octadic capacitor) makes it completely obsolete when compared to a Tier 3 Crafter from RFTools set to Fast craft mode.

For comparison: 7 cobblestone generators (producing 64 via world interaction upgrades) being fed into an RFTools Crafter to make quadruple compressed cobblestone does not actually input enough cobblestone fast enough to keep up. These same seven generators go into an EnderIO Crafter and fills it up immediately.

If I may recommend lowering the RF required per craft (available in the EnderIO.cfg under the "autocrafter settings" section) to make it feel more like a potential T2+ crafting option.

**Comment by drz2k** [comment]
XU Crafting node isnt using power at all. The RFTools crafter is pointless!

Seriously ? ;)

**Comment by Kalbintion** [comment]
I'm well aware of the XU crafting node not taking power, but that isn't the point. In a pack about tiered progression, one would expect the machines to be better, whether or not this is in terms of speed, the amount of power they generate, or the power consumption. Things get progressively better in a tiered system.

**Comment by bookerthegeek** [comment]
So you are saying that as it stands, you feel that the ender I crafter has no benefit over the rf crafter? No benefit at all?

**Comment by drz2k** [comment]
The EIO Crafter has auto pull and push. Thats a nice benefit depending on situation. 

Also ... I wont balance every little thingy or I would never be ready. Spruce saplings costs the same amount of cellulose to synth as oak trees. Hey, you must change that since spruce trees yield more wood!

Lets keep it at a sane level.
