### ISSUE TITLE
Server problems

### ISSUE THREAD

**Issue by Olli0203** [MyM-ModpackTeam/GalacticScience#57]
Hey there :D

Today I wanted to start a server in my machine to play with a friend ad noticed sth...
It was loading until one point where it said:

Detected following JVM Error
cant find command "cat"
cant start server, exiting...

(thats about the text that stood there)
would be nice to know whether its something on my machine i have to change or a problem with
the code in general.

Olli :D

**Comment by SirWilli** [comment]
Which os? 
32 or 64 bit system?
Java version?

**Comment by Olli0203** [comment]
64 bit

**Comment by Olli0203** [comment]
in general those things work fine :D

**Comment by Olli0203** [comment]
oh and its Java update 66

**Comment by Olli0203** [comment]
java 8

**Comment by Olli0203** [comment]
well sry i am a bit cofused ...
its windows 10
64 bit 
java 8 update 66

**Comment by SirWilli** [comment]
I deleted your other comments, this is no chat system so please create one comment and not for each line one.

**Comment by Olli0203** [comment]
ok

**Comment by SirWilli** [comment]
Do you have a java-test.log in your folder? If yes post the content via www.pastebin.com please
