### ISSUE TITLE
Dalek Mod crashes on Start

### ISSUE THREAD

**Issue by Rimgar** [MyM-ModpackTeam/GalacticScience#59]
Hey there,

The modpack crashes on Start when initializing the dalek mod (initialization phase 2)
When I disable the dalek mod the game start without problems.
I updated the pack yesterday and it worked, today it didn't.
Reloading the pack doesn't work either.

I'm using the FTB-Launcher on Windows 7 64Bit

See log:
http://pastebin.com/Pzj6j1gV

**Comment by SirWilli** [comment]
Are you sure you did redownload the complete pack?
As I can't reproduce the issue.

**Comment by Rimgar** [comment]
I'm sure with that. My friend had the same problem.
Now the pack starts without any problem (without redownloading or any other change).
I can't explain that.

Sorry for the trouble and thanks for your effort. I will close this issue.
