### ISSUE TITLE
Server unresponsive after creating star

### ISSUE THREAD

**Issue by tentonaxe** [MyM-ModpackTeam/GalacticScience#6]
When i drop a Heart of Star into fire (inside an oxygen bubble), it absorbs the fire, i see it explode, and a star appear, however, the server is unresponsive and times out. The server stays in this state for 20-30 minutes, then becomes operational again. When rejoining, i find the fire all re-lit, no damage as if no explosion occurred, and the Heart of Star is sitting in the fire, meaning, it didn't craft a star. I can then pick up the heart of star and repeat the process.

Server admin couldn't find anything relevant to this in the logs.

I cannot recreate this issue in SSP. We're using the version of GS that's on the MyM Launcher.

Problem continues to occur even after a server restart. No additional mods. The explosion happens at y20 with no other mod blocks in the area, right at the edge of an oxygen bubble.

I would have posted this on supermassive tech, but, with no logs, and being unable to re-create this in ssp, I can't prove that it's caused by that mod or some other mod integration.

**Comment by SirWilli** [comment]
I will try to reproduce this on my test server later.

**Comment by SirWilli** [comment]
Hm, I can't reproduce this issue. Can you reproduce it or is it only a one time thing?

**Comment by tentonaxe** [comment]
I'll try it again tomorrow. I was able to reproduce it before, happened every time i tried (5-6 different times)

**Comment by SirWilli** [comment]
Which version of forge, galacticraft and supermassivetech?

**Comment by tentonaxe** [comment]
forge 1448, GC 3.0.12.345, SMT 0.2.0-alpha-86

**Comment by tentonaxe** [comment]
I just tried again, this time using oxygen sealers instead of oxygen bubble, and it worked. Also, on mars instead of on the moon, and it worked, no crash. Will try with a bubble generator next on mars

**Comment by tentonaxe** [comment]
Yup, it all works. guess whatever it was fixed itself.

**Comment by SirWilli** [comment]
Okay, great.

**Comment by shadowpanther** [comment]
Currently, lighting a fire inside an oxy-sealed space (on the Moon, if that matters) crashes the server. Lighting fire inside an oxy-bubble doesn't crash the server.

**Comment by NolanSyKinsley** [comment]
That will probably be fixed in an upcoming update to the pack, it has been fixed in Galacticraft, the pull request just needs to be tested and fully vetted. Check #24 for future information on that update.
