### ISSUE TITLE
MineChem Chemical Synthesis - No Recipe's

### ISSUE THREAD

**Issue by avur** [MyM-ModpackTeam/GalacticScience#60]
Good afternoon, I am using Galactic Science V. 1.4.15 and MineChem 5.0.5. It seems the Chemical Synthesis will not accept ANY recipe's period. This causes a massive problem in moving forward. Here is just one recipe showing proof it is not accepting the recipe, and I have verified on multiple other instances it should be working the way I am trying.

![ss 2015-12-05 at 03 36 39](https://cloud.githubusercontent.com/assets/16170231/11610359/582d4448-9b66-11e5-87cb-2ecc2777e271.png)

**Comment by Bennyboy1695** [comment]
Is this on the server or in single player ? If on single player trying allowing cheats (if not already allowed) and doing "/mt reload" to give the scripts a reload and then try a recipe again, make sure to check the recipe hasnt been removed using NEI aswell

**Comment by drz2k** [comment]
Well this is a non valid recipe. Try a valid one....
