### ISSUE TITLE
Glitch/bug

### ISSUE THREAD

**Issue by Pigbull320** [MyM-ModpackTeam/GalacticScience#66]
I will try my best to explain this in as much detail as possible.

I logged back into my single player world and keep falling into the void, on earth.
I had 'solar fray' affect.
I turned LAN on and enabled cheats so i could go into creative. i then made a rocket and went back to the moon, it took me a minute but i found my base.
I had no grave, (i could find at least).

I have screen shots as well, i don't know what caused this, my only guess would be i closed the game while it was not responding.
![2015-12-19_17 35 58](https://cloud.githubusercontent.com/assets/16366090/11915591/43548ef8-a67b-11e5-8774-2c4dcaaa1367.png)
![2015-12-19_17 45 41](https://cloud.githubusercontent.com/assets/16366090/11915592/435a7c46-a67b-11e5-8025-778e7bc2c3a1.png)
![2015-12-19_17 35 56](https://cloud.githubusercontent.com/assets/16366090/11915593/4361170e-a67b-11e5-8f63-85336fcfbfd8.png)

**Comment by SirWilli** [comment]
Hm, weird. You get teleported to the moon if you switch the world to the overworld so it seems that nothing teleported you.

Did it happen only once?

**Comment by Pigbull320** [comment]
This got me kind of unmotivated to continue playing once i lost all my things, if you want i can give you the world save or try re-create it. (i really don't want to try and re-create it but i will).

**Comment by SirWilli** [comment]
I will close this for now as there is not really a way to reproduce it and as it happened only once and not frequently it shouldn't be a big issue.
