### ISSUE TITLE
Cannot take oil in crucible

### ISSUE THREAD

**Issue by korncover** [MyM-ModpackTeam/GalacticScience#67]
Since the new update. We can't take the oil in a crucible, i tested it even with 5000mb of oil its not working. Every new player on the server is asking the same thing, why its not working. Since the modpack is based on exploring other planet, how can we go to other planet without oil (to do fuel)

**Comment by SirWilli** [comment]
Same issue in singleplayer?

**Comment by korncover** [comment]
same issue in single player

**Comment by drz2k** [comment]
Issue reproducable.

Workaround for now : You can use an EIO Tank to fill the canister.

This seems to be related to GC canisters since old EX Astris and Nihilo have the same problem

**Comment by SirWilli** [comment]
Galacticraft issue: https://github.com/micdoodle8/Galacticraft/issues/1993
