### ISSUE TITLE
Bug with relocator and minechem (Multiplayer server)

### ISSUE THREAD

**Issue by Synapse15** [MyM-ModpackTeam/GalacticScience#68]
There is a bug whereby I cannot seem to transfer chemicals in the relocator with the Filter module. I tested it in singleplayer and it works fine, just that in a server is does not seem to filter out the chemicals. The ID is different on both servers for the same chemical. Does anyone know a workaround?

**Comment by SirWilli** [comment]
Doesn't work on the MyM server or private?

**Comment by Synapse15** [comment]
I created a private server on my computer to play with my friends, it doesnt work. I restarted the server a few times to no avail. I have not tried it on the mym server yet.

**Comment by SirWilli** [comment]
Hm okay, can you post few screenshots of the setup so I can reproduce it?

**Comment by Synapse15** [comment]
Sure! Thank you! :)
This is the setup
![test](https://cloud.githubusercontent.com/assets/13861806/11975956/2cc5f574-a9ae-11e5-9605-c6398c31c4cd.png) 
This is the item ID on the singleplayer
![untitled1](https://cloud.githubusercontent.com/assets/13861806/11975979/7fddbf4e-a9ae-11e5-8a56-4096d97465d5.png)
This is the item ID on the multiplayer server
![untitled2](https://cloud.githubusercontent.com/assets/13861806/11975983/8a08081c-a9ae-11e5-8790-836d3bcfecd5.png)

**Comment by SirWilli** [comment]
What's your filter which works in SP but not MP?

**Comment by Synapse15** [comment]
The module filter

**Comment by SirWilli** [comment]
I mean which filter from this list:
![](https://i.imgur.com/HvtRIQP.png)

**Comment by Synapse15** [comment]
Customizable text is the one not working. The rest seems to work fine.

**Comment by SirWilli** [comment]
Then I also need the Text you are using

**Comment by Synapse15** [comment]
Cellulose

**Comment by Synapse15** [comment]
It does not work with any other chemicals as well, not only cellulose

**Comment by SirWilli** [comment]
Ok, I could reproduce it and reported it:
https://github.com/Dynious/RefinedRelocation/issues/385

**Comment by Synapse15** [comment]
Thank you! :+1:
