### ISSUE TITLE
synthetizer, decomposer and fusion chamber bug

### ISSUE THREAD

**Issue by MrWisski** [MyM-ModpackTeam/GalacticScience#69]
From our ticket system:
"The synthetizer, decomposer and fusion chamber from chemcraft aren't filling at 100% energy, so we cant craft venus crystals or things like this. they fill between 5% and 20% and stay there."

"Only happening on the MyM server, for everybody."

can confirm this is in fact happening, tho no clue as to the why, as i'm pretty sure we're running the stock configs for everything (Maybe a cauldron issue?) :
![chemicaldecomposer](https://cloud.githubusercontent.com/assets/11817687/11957222/6e5f37f0-a88e-11e5-8c0b-883725250598.PNG)

![chemsynth](https://cloud.githubusercontent.com/assets/11817687/11957232/8cb1c5d8-a88e-11e5-8bbc-3844b588630d.PNG)

**Comment by MrWisski** [comment]
Both devices are filled to their max - 10k RF and 100k RF, btw.

**Comment by drz2k** [comment]
If this is only happening on the mym server id suggest hotfixing it by editing the minechem.cfg and setting

    # Max power that the fission reactor can hold
    I:maxFissionStorage=10000000

    # Max power that the fusion reactor can hold
    I:maxFusionStorage=10000000

    # Max power that the synthesizer can hold
    I:maxSynthesizerStorage=500000

slightly higher.

**Comment by SirWilli** [comment]
Seems that the server had the default minechem config. Config updated and fixed now.
