### ISSUE TITLE
Crash to login screen when pressing button in Router Reborn chest advanced GUIs

### ISSUE THREAD

**Issue by cjo9900** [MyM-ModpackTeam/GalacticScience#7]
Playing Galactic Science 1.3.2

version: RouterReborn-1.7.10-1.2.0.31-universal.jar
Mantle-1.7.10-0.3.2.jar
GalacticScience_Tweaks-1.1.jar

When pressing any button in the opened interface I receive the following exception
Tested in all of the Advanced Chest GUIs

[22:09:18] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at router.reborn.RouterNetPackage$Handler.onMessage(RouterNetPackage.java:261) ~[RouterNetPackage$Handler.class:?]
	at router.reborn.RouterNetPackage$Handler.onMessage(RouterNetPackage.java:67) ~[RouterNetPackage$Handler.class:?]

Full log files
https://gist.github.com/cjo9900/e22a6b8f2095bdec5f35

Test case 
Create a new world 
Change to creative and get a "Upgrade Packager Advanced" from Router Reborn
Then Right click with the item selected to open the GUI
(as per http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176322-router-reborn-1-1-6?comment=236)
Then press any button in the GUI, i.e. 2x2 or 3x3

Crash occurs
"Connection lost A Fatal error has occurred, this connection is terminated"

Testing shows that by removing mods that the error is linked to GalacticScience_Tweaks-1.1.jar as removing that mod means the error goes away.
With all other mods in the pack present the issue is not seen.

**Comment by SirWilli** [comment]
Are you sure you disabled not any other mod? As I still could reproduce the issue after disabling the Tweaks mod.

**Comment by cjo9900** [comment]
Did some more testing and it seems to be only when the world was created with that mod enabled, that the error occurs. 
As my earlier testing was to create a new world each time.

Test 1
Create world with all mods enabled
Error occurs

Remove  GalacticScience_Tweaks 
Error still occurs

Test 2
Create world without GalacticScience_Tweaks mod enabled
(Creative or use NEI to switch to creative on first death due to void world)
Error does not occur

Add back GalacticScience_Tweaks 
Error does not occur

So it is not the GalacticScience_Tweaks on its own but something it is doing when creating the world, as I assume that this is mod that relocates the player to the moon and gives them the starting equipment.

**Comment by SirWilli** [comment]
Then it probably has something to do with the location or equipment.

**Comment by drz2k** [comment]
I saw that behavious when it tries to pull information from some special GC machines. Cross mod compatibility issue.
