### ISSUE TITLE
Overworld Probs

### ISSUE THREAD

**Issue by sunny006** [MyM-ModpackTeam/GalacticScience#70]
I created a multiplayer server for my friends and today we tryed to visit the overworld. But when we reached overworld, it wasnt loaded. So i tested in single player mode and i always landed on the moon. So ... what sould i do ?? ( srry for my bad english)

**Comment by SirWilli** [comment]
Overworld is disabled, you shouldn't go there

**Comment by sunny006** [comment]
kk
