### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by FrozenLiberty** [MyM-ModpackTeam/GalacticScience#71]
I tried sometimes, changed my pc language,install java 7 64 bit.When I click Launch it starts and load. At 7/7 I see this message ''Java Platform SE Binary Stopped working''. I need help ...

**Comment by SirWilli** [comment]
Please post your complete client log.

**Comment by FrozenLiberty** [comment]
I cant send message because max message 262144 ...

**Comment by SirWilli** [comment]
You should use gist https://gist.github.com/

**Comment by FrozenLiberty** [comment]
https://gist.github.com/FrozenLiberty/7df14f8f2ee99e51b01b

**Comment by SirWilli** [comment]
Please try to reinstall the pack and if this doesn't fix it try it with java 8

**Comment by FrozenLiberty** [comment]
I will try with java 8...

**Comment by FrozenLiberty** [comment]
It isnt worked sorry :/

**Comment by SirWilli** [comment]
Does any other pack on FTB Launcher work? Did you try MyM Launcher yet?

**Comment by FrozenLiberty** [comment]
Especially not... and I didnt try mym launcher because I cant found it.

**Comment by FrozenLiberty** [comment]
Can you send me MyM launcher link ?

**Comment by FrozenLiberty** [comment]
Im trying with Curse Minecraft addon ...

**Comment by SirWilli** [comment]
www.mineyourmind.net

**Comment by FrozenLiberty** [comment]
It isnt worked at curse.Same Problem it shows me debug

**Comment by drz2k** [comment]
Sounds like a enviromental path issue. First try installing in a subdir that isnt affected by UAC. Then check your java enviroment variables.

Give feedback on mym launcher or vanilla mc.

**Comment by FrozenLiberty** [comment]
http://i65.tinypic.com/24z8yuo.png It's the image :/ And I tried At Infınıty same issue you can see

**Comment by drz2k** [comment]
http://lmgtfy.com/?q=mym+launcher
