### ISSUE TITLE
Refined Relocation's Sorting Barrel not working properly

### ISSUE THREAD

**Issue by PF98** [MyM-ModpackTeam/GalacticScience#73]
Applying a Redstone upgrade and a Redstone facade doesn't make a Sorting Barrel emit a redstone signal if full, if it receives items from a linked sorting chest.

**Comment by SirWilli** [comment]
Sounds like a mod bug, please report it to the mod author.

**Comment by drz2k** [comment]
RR is known to have some bugs. As SW said, report it to the moddev.
