### ISSUE TITLE
No recipe for "Mobius Unstable/Stable Ingot"

### ISSUE THREAD

**Issue by Dante2178** [MyM-ModpackTeam/GalacticScience#74]
"Mobius Unstable/Stable Ingot" is an Extra Utilities item that is originally crafted with the psuedo-inversion sigil, an iron ingot, and a diamond, and is used to craft tools and most importantly the Kikoku, my personal most favourite item across all mods. However, because the recipe for unstable ingots has been changed to a minechem recipe, and the division sigil, (and with it the pseudo-inversion sigil) has been removed, "Mobius Unstable/Stable Ingots" are unable to be crafted and has no recipe.

**Comment by drz2k** [comment]
First - This has not be to be an "issue" ... it could just be intended for balancing.

But ... why dont you simply make some stable ingots and go ahead with your favorite items?

http://imgur.com/xNhRZ9x

**Comment by drz2k** [comment]
Pick and Shovel - RR Pickaxe
Super Builders - im quite sure theres one in the rewards given out if no one messed it up
Kikoku - The Ender/Eviscerator or if you really want this weapon, theres an alternate way to get it (check ftb wiki)
The shears ... well theres something similar in the tadis area ...

**Comment by Dante2178** [comment]
I am aware that there is an alternate way to get the Kikoku, however, it only has a 50% chance to work and if it fails will never work.
