### ISSUE TITLE
No recipe for "Mobius Unstable/Stable Ingot" v. 2.0

### ISSUE THREAD

**Issue by Dante2178** [MyM-ModpackTeam/GalacticScience#75]
As stated before, the recipe for "Mobius Unstable/Stable Ingots" has been removed. This is the solution I received:

"Pick and Shovel - RR Pickaxe
Super Builders - im quite sure theres one in the rewards given out if no one messed it up
Kikoku - The Ender/Eviscerator or if you really want this weapon, theres an alternate way to get it (check ftb wiki)
The shears ... well theres something similar in the tadis area ..."

However, this does not solve or fix the problem in any way. I am aware of all these items. I am also aware that there is another way to obtain the Kikoku, but, this only has a 50% chance of working, and will ALWAYS have the same result every time on a given world, and in my particular world it has failed and awarded me a 'Rick Rolled Numa Numa' music disc instead.

I think a better solution (one that I was able to do myself quickly to test) was to add a quest in the 'Silly Willi's' tab that traded the stable version of the unstable ingot, an emerald, and 3 obsidian for a "Mobius ubstable/stable ingot." This took me less than 7.5 minutes (I even timed myself) to do.

**Comment by TheRealSmurf** [comment]
Can you pleeaase add that quest into the game?? I want the kikkoko to!

**Comment by Dante2178** [comment]
I am not a maker of this particular modpack, so I am unable to add this into the game. However, some of the moderators of this page might be able to add something similar.

**Comment by 1337-JohnnyMan** [comment]
Can you at least show us how to add a quest?

**Comment by Dante2178** [comment]
Sure. I will post a YouTube self-fix tutorial video in a few weeks. I will give the modders a little time to fix the situation themselves first, though, (hence the few week delay) because I know the frustration firsthand of having a swath of users trying to fix a problem in my program themselves before I even had react to the problem.

**Comment by drz2k** [comment]
How is this an "issue" that needs to be "fixed" ?

Maybe its just intended? You should mark this as a feature or proposal request ....

Seriously, the way you put in this feature request makes me want to ignore it.

Also, why not use the old issue # ?

**Comment by drz2k** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/issues/75

**Comment by Dante2178** [comment]
I would like to start off with an apology for making a duplicate page. I am a little new to github..

The issue is that items are missing from the game. Missing items in a modpack make the modpack extremely frustrating to try to play for myself and others. However, I appreciate your suggestion of making this a feature request, even though I feel it is not fitting the theme of my issue report. I am trying to be considerate here, and I am trying my best not to 'go behind the backs' of the modpack makers and giving them trouble in the process; but as many of my friends are frustrated with this issue with the game, somebody needs to help them soon.

In addition, if you think that recipe does not fit the theme of the pack, it is not difficult to choose a different one instead, I was simply using this one as an example. I would definitely appreciate any help with this you can provide with another 'quest recipe' or another method of obtaining this missing item, as, to be perfectly honest, coding is my strong suit; not balancing cost and player accessibility. What do you think would be a better option of getting these items?

**Comment by drz2k** [comment]
Well, alright :)

Missing items could be just intended in a modpack, see the XU Generators for example.

Since I already put in Generikbidium for the normal stable nuggets I would use the fusion to further "Clean" the material to enhance it.

Chemicals.addElement(773,"MB","Mobiate","Metalloid","Liquid","Stable");
Synthesiser.addRecipe([<minechem:minechemElement:773>],<xxx>,true,50000);

(xxx = /mt hand on that mobius nugget to get the name)

Kinda like this. If programming is your stuff and your new to github - create a pull request with the completed addition from above! ;)
