### ISSUE TITLE
Wrenches are annoying

### ISSUE THREAD

**Issue by tterrag1098** [MyM-ModpackTeam/GalacticScience#77]
The only wrench that seems to work properly is the RR wrench and it's ugly as sin. Perhaps make the yeta wrench not gated by mars materials so it can be used early game? Or complain to GC, PA, and and EA that their wrenches suck >.>

**Comment by Slind14** [comment]
I'm not sure if there is any special reasoning around it. The pack creator is mia atm, so there won't be a change until he is back. Cheat one in for now :)
