### ISSUE TITLE
Cant use oxygen sealers 

### ISSUE THREAD

**Issue by scrappy350** [MyM-ModpackTeam/GalacticScience#80]
everytime i try to setup a oxygen sealer to get a star it jsut crashes and corrupts my world 
here is the log
http://paste.feed-the-beast.com/view/cc766916

**Comment by SirWilli** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/issues/79

Already fixed in the next update, just need to wait for FTB.

**Comment by SirWilli** [comment]
Update is now live.
