### ISSUE TITLE
Thermal Armor doesn't work on venus

### ISSUE THREAD

**Issue by Da-Technomancer** [MyM-ModpackTeam/GalacticScience#82]
Basically what the title says, even with thermal armor, I overheat on venus. It worked a couple updates ago. (the update before ex astris reborn was added)

**Comment by SirWilli** [comment]
Confirmed issue, I assume that issue got caused by an API change in galacticraft. 
Not sure what to do about this issue as 4Space seems to no longer get updates.

**Comment by Mannol-zz** [comment]
Same goes for Pluto btw. It wouldn't surprise me if it's all the modded planets. 
I tried taking off the thermal armor and putting it back on btw.. when I had the armor off, the damage was more, so the thermal armor is not completely useless.

**Comment by random51** [comment]
Same for Mercury. :)
