### ISSUE TITLE
Offline playing

### ISSUE THREAD

**Issue by TengriTorok** [MyM-ModpackTeam/GalacticScience#83]
Some times i want to play offline, because i have no internetconnetion aviable.
if i start the mod (i love it), it crashes.
i have tested to disable some included mod and i see that the mod modularsystem is the problem.
when i disable it i can play offline, when it is active then galactic science crashes.

**Comment by SirWilli** [comment]
Can you post the crash report found in the crash-reports folder?

**Comment by TengriTorok** [comment]
https://gist.github.com/TengriTorok/edcc569d87873424f726
this happens on two different machines.
On both can i play, when i disable modularsystems

**Comment by SirWilli** [comment]
Thanks,  I reported it to the mod author: https://github.com/TeamCoS/Modular-Systems/issues/110
You can leave the mod out for now as it has another issue which will crash you if you use blocks from the mod.

**Comment by TengriTorok** [comment]
Hi,
disabling Modularsystem has an effect to the scripts in the mod. an exemple and NEI shows no recipe for automaticsieve and i cant also craft one.
Minetweaker.log: https://gist.github.com/TengriTorok/dfc60410cee42e401e44

**Comment by SirWilli** [comment]
Probably because of the missing items, you would need to edit the scripts and remove all recipes which contains modular systems blocks/items.

**Comment by Homeless-One** [comment]
Since I'm inexperienced with this sort of thing, would it be best to just wait until a fix is released? Or should I attempt to do the above?

**Comment by TengriTorok** [comment]
You have to comment out with "//" only four or five lines in replacedRecipes.zs in the folder scipts.
search in the File for the section modularsystems and command every linear there.
i have it done and it  works for me.

**Comment by Homeless-One** [comment]
So for every modular systems recipe in that file I should put //<modularsystemrecipe>// ? And what file should I use to open it, will notepad do?

**Comment by TengriTorok** [comment]
every line "in" the section //(modularsystemrecipe)//.
notepad isnt a good idea, because it open the File without linefeed. wordpad is a better choice.
