### ISSUE TITLE
invalid private pack

### ISSUE THREAD

**Issue by archiecarrot123** [MyM-ModpackTeam/GalacticScience#86]
code THX2MYM  or thx2mym do not work in ftb v1.4.11

**Comment by drz2k** [comment]
Its a LISTED pack on FTB ...

**Comment by archiecarrot123** [comment]
on linux the last time it was listed was a couple of ftb updates ago

**Comment by drz2k** [comment]
Ask FTB about FTB launcher issues please. As said its a listed 3rd party pack and will stay for quite some months in this state, after that, the pack code should work again.
