### ISSUE TITLE
invalid code pack

### ISSUE THREAD

**Issue by archiecarrot123** [MyM-ModpackTeam/GalacticScience#87]
archiecarrot123 commented 17 hours ago
code THX2MYM or thx2mym do not work in ftb v1.4.11

**Comment by archiecarrot123** [comment]
on linux the last time it was listed was a couple of ftb updates ago

**Comment by SirWilli** [comment]
What are you talking about? The pack is listed as caithleen already said in your other issue.
Does it not show up for you?

**Comment by archiecarrot123** [comment]
no, it does not

**Comment by archiecarrot123** [comment]
the only 3rd party packs that show are blast off and magic farm 2 :adventures in technology

**Comment by SirWilli** [comment]
Try to redownload the FTB Launcher

**Comment by archiecarrot123** [comment]
ok i did

**Comment by archiecarrot123** [comment]
but i cannot run it because it has brackets and i cannot rename it because i cannot find it for some strange reason

**Comment by SirWilli** [comment]
You should solve that issue then first.
