### ISSUE TITLE
No Starter House?

### ISSUE THREAD

**Issue by RedGoblin** [MyM-ModpackTeam/GalacticScience#89]
Deleted the world a few times thinking it did not load properly. After a third time-- thinking maybe it's a problem. 

Looked around to see if this was an issue, seems like it's just me?

**Comment by drz2k** [comment]
Multiplayer or Single? If single, do you get to choose which of the 2 bases you want to start with?

**Comment by RedGoblin** [comment]
Multiplayer.

First thing is making a map, spawns me underground and had to spam jump too not suffocate. 

I was like, "Man, this is hardcore."

Then my friend and I was looking at the quest book, being confused on how to get these items.

Thus youtube lets play showed me the truth.

**Comment by Slind14** [comment]
Do you spawn on the moon? If not /op your self from console and use /cofh tpx -28 to get there. The starter building should be near the location that it is teleporting you to.

**Comment by RedGoblin** [comment]
Yea. It spawns me underneath moonturf.

**Comment by SirWilli** [comment]
Where did you download the server and which version?

**Comment by RedGoblin** [comment]
Downloaded from FTB Launcher - v1.5.7

**Comment by RedGoblin** [comment]
@Slind14 - Did the /cofh - just tells me that it's successful but didn't move me, since I pretty much just logged off at this spot when there was no building.

**Comment by RedGoblin** [comment]
Seems like I just made a single player and just copy-paste that world data onto the remote server. Seems to work okay so far, just need to wait for my friend to log on.

**Comment by SirWilli** [comment]
I can't reproduce your issue. Downloaded the server from ftb launcher, launched the server, joined the server and spawned perfectly in front of the starter base.

**Comment by RedGoblin** [comment]
@SirWilli Odd. I re-downloaded and launched it and still the same. Though in the previous comment found a way around it though. Thanks though. It's just my luck.

**Comment by Slind14** [comment]
Is your server in online or offline mode?

**Comment by RedGoblin** [comment]
It's online mode.

**Comment by RedGoblin** [comment]
Got it to work finally, I realized that there was a "world" folder. I typically delete it since I tend to make a name for the world. Since I need to update the properties to change the port# due to the server I'm using.

**Comment by SirWilli** [comment]
-.- No wonder then.
Where else should the starter base saved?
