### ISSUE TITLE
Quest Super massive tech crafting glich

### ISSUE THREAD

**Issue by minderrr** [MyM-ModpackTeam/GalacticScience#90]
Ill just get straight to the point in Storage solutions a quest where you need to craft black hole storage and when i do it doesnt register that i craft it the same gose in the stars align (been to pluto?) where i have to craft star harvester i did but it does not register help.

**Comment by SirWilli** [comment]
Probably related to the mod update. Looking into it.

**Comment by SirWilli** [comment]
The following crafting tasks got fixed:
- 4. Black hole storage
- 7. Been to pluto?

If I forgot any please let me know.
