### ISSUE TITLE
Bug in space

### ISSUE THREAD

**Issue by Paprd** [MyM-ModpackTeam/GalacticScience#92]
I flew to the space (on Asteroids) and i am just floating in space, i can't land, i can't do anything. I tried this on second world and it was good, but in my main world it is broken. Can somebody help me what to do ?

**Comment by SirWilli** [comment]
Does the client log show anything?

**Comment by Paprd** [comment]
No, it isn't bug in client, just bug in game, i can't land because i am flying down a then up.

**Comment by SirWilli** [comment]
So you are stuck? Delete your player file then.
