### ISSUE TITLE
can you please fix this

### ISSUE THREAD

**Issue by archiecarrot123** [MyM-ModpackTeam/GalacticScience#93]
Labels

duplicate
support
Milestone

No milestone
Assignee

No one assigned
Notifications

  Unsubscribe
You’re receiving notifications because you authored the thread.
2 participants

@archiecarrot123 @SirWilli
@archiecarrot123
archiecarrot123 commented 10 days ago
archiecarrot123 commented 17 hours ago
code THX2MYM or thx2mym do not work in ftb v1.4.11
 @archiecarrot123
  
archiecarrot123 commented 10 days ago
on linux the last time it was listed was a couple of ftb updates ago
 @SirWilli
Owner
SirWilli commented 10 days ago
What are you talking about? The pack is listed as caithleen already said in your other issue.
Does it not show up for you?
 @SirWilliSirWilli added duplicate support labels 10 days ago
@archiecarrot123
  
archiecarrot123 commented 10 days ago
no, it does not
 @archiecarrot123
  
archiecarrot123 commented 10 days ago
the only 3rd party packs that show are blast off and magic farm 2 :adventures in technology
 @SirWilli
Owner
SirWilli commented 10 days ago
Try to redownload the FTB Launcher
@archiecarrot123
  
archiecarrot123 commented 2 days ago
ok i did
 @archiecarrot123
  
archiecarrot123 commented 2 days ago
but i cannot run it because it has brackets and i cannot rename it because i cannot find it for some strange reason
 @SirWilli
Owner
SirWilli commented 2 days ago
You should solve that issue then first.
 @SirWilliSirWilli closed this 2 days ago
  

feed of last time

**Comment by archiecarrot123** [comment]
i am using FTB_laucher (3).jar (before i renamed it)

v1.4.11

**Comment by SirWilli** [comment]
???

**Comment by drz2k** [comment]
Stop open duplicate issues with bad description on whats wrong - instead fix your ftb client installation. If you need support on your FTB client - head over to the FTB support.

**Comment by archiecarrot123** [comment]
Does anyone have linix opensuse because I do, just to let you know.

On 30/01/2016 9:24 PM, "drz2k" <notifications@github.com> wrote:
>
> Stop open duplicate issues with bad description on whats wrong - instead
fix your ftb client installation. If you need support on your FTB client -
head over to the FTB support.
