### ISSUE TITLE
Linux Server Script

### ISSUE THREAD

**Issue by Wdrussell1** [MyM-ModpackTeam/GalacticScience#96]
This is more of a gripe that is becoming more common and is bloody annoying. Instead of some crazy coded start script. Or some silly junk. How about we go with the simple ones? Just cause i know linux doesnt mean i want to have to read what the heck was going through your mind when you created the script just to make it work on my linux server.

**Comment by SirWilli** [comment]
If you just say you don't like it and don't say a real reason and just don't use it instead of complaining about it without a real reason.

**Comment by Wdrussell1** [comment]
load this script into a linux server and try it. It doesnt work. Why? cause some one tried to get fancy. KISS. Always a term to live by.

**Comment by SirWilli** [comment]
Worked fine the last time I used it. 
Just tested again, still works fine.

- wget ...
- unzip ...
- `eula=false` -> `eula=true`
- bash ServerStart-Other.sh

done, server running
