### ISSUE TITLE
GalactiCraft spawner doesn't work

### ISSUE THREAD

**Issue by Gamer0072** [MyM-ModpackTeam/GalacticScience#99]
Well all GalactiCraft spawner doesn't spawn any mobs in dungeons and taken with dollys I don't know if it's related with the modpack but .. yes

**Comment by SirWilli** [comment]
Modpack version?

Does it not work in the dungeon or after you moved it with a dolly?

**Comment by Gamer0072** [comment]
1.5.7 and both

2016-02-08 12:35 GMT+01:00 SirWilli <notifications@github.com>:

**Comment by SirWilli** [comment]
Try latest modpack version.
